### ISSUE TITLE
erros envolvendo o particípio passado

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#100]
@arademaker, por acaso, usando as formas do MorphoBr para testar a PorGram, me deparei com o seguinte erro:

` grep -P "^latidos\t" ~/MorphoBr/verbs/verbs-a*.dict`

> /home/leonel/MorphoBr/verbs/verbs-abm.dict:latidos	later+V+PTPST+M+PL
> /home/leonel/MorphoBr/verbs/verbs-abm.dict:latidos	latir+V+PTPST+M+PL
> /home/leonel/MorphoBr/verbs/verbs-abm.dict:latidos	latir+V+PTPST+M+SG

A terceira forma é claramente espúria: o particípio singular termina sempre em _s_.  Procurando por outros casos análogos, encontrei formas do particípio masculino singular terminadas também em _as_, o que não existe na língua portuguesa. Veja:

`awk '$1 ~ /.+s$/ && $2 ~ /PTPST\+M\+SG/' ~/MorphoBr/verbs/verbs-a*.dict`

> frangidas	frangir+V+PTPST+M+SG
> frangidos	frangir+V+PTPST+M+SG
> fritas	fritar+V+PTPST+M+SG
> fritos	fritar+V+PTPST+M+SG
> latidas	latir+V+PTPST+M+SG
> latidos	latir+V+PTPST+M+SG
> premidas	premir+V+PTPST+M+SG
> premidos	premir+V+PTPST+M+SG
> ringidas	ringir+V+PTPST+M+SG
> ringidos	ringir+V+PTPST+M+SG
> 

Existem mais casos análogos? No caso do particípio, as terminações _o_ e _a_ marcam, de forma consistente na língua, respectivamente o masculino e o feminino, o plural de ambos os gêneros sendo marcado por _s_. Ou seja, as seguintes correspondências são obrigatórias:

Terminação | Etiquetas
------------ | -------------
o | PTPST+M+SG 
a | PTPST+F+SG
os | PTPST+M+PL 
as | PTPST+F+PL

Desvios desse padrão como os apresentados constituem erros do recurso que precisariam ser corrigidos.

**Comment by leoalenc** [comment]
@arademaker, de fato, continuando o exame de formas do particípio passado não reconhecidas pela PorGram, encontrei também PTPST+M+SG terminado em _a_. Veja:

 `grep -Ph "^latid[oa]s?\t" ~/MorphoBr/verbs/verbs-a*.dict`

> latida	later+V+PTPST+F+SG
> latida	latir+V+PTPST+F+SG
> latida	latir+V+PTPST+M+SG (ERRO)
> latidas	later+V+PTPST+F+PL
> latidas	latir+V+PTPST+F+PL
> latidas	latir+V+PTPST+M+SG (ERRO)
> latido	later+V+PTPST+M+SG
> latido	latir+V+PTPST
> latido	latir+V+PTPST+M+SG
> latidos	later+V+PTPST+M+PL
> latidos	latir+V+PTPST+M+PL
> latidos	latir+V+PTPST+M+SG (ERRO)
>

**Comment by vcvpaiva** [comment]
Leonel,
a primeira linha tb tem que estar errada, não e?
não existe o verbo "later"!!

latida later+V+PTPST+F+SG

**Comment by arademaker** [comment]
@vcvpaiva see http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=104176 and https://michaelis.uol.com.br/moderno-portugues/busca/portugues-brasileiro/later/

**Comment by leoalenc** [comment]
> @vcvpaiva see http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=104176 and https://michaelis.uol.com.br/moderno-portugues/busca/portugues-brasileiro/later/

@vcvpaiva, @arademaker tem razão, existe o verbo _later_.

**Comment by leoalenc** [comment]
@arademaker, usando dados do MorphoBr na PorGram, detectei outro tipo de erro  envolvendo o particípio passado, que aliás já ocorre com o verbo _latir_ mencionado acima: ao lado da forma do masculino singular, 20 verbos apresentam uma outra forma, redundante, sem marcação de gênero e número:

`grep -Ph "\t.+PTPST$" verbs-a*.dict`
 

> advindo	advir+V+PTPST
> avindo	avir+V+PTPST
> contravindo	contravir+V+PTPST
> convindo	convir+V+PTPST
> desavindo	desavir+V+PTPST
> desconvindo	desconvir+V+PTPST
> devindo	devir+V+PTPST
> entrevindo	entrevir+V+PTPST
> frangido	frangir+V+PTPST
> frito	fritar+V+PTPST
> intervindo	intervir+V+PTPST
> latido	latir+V+PTPST
> obvindo	obvir+V+PTPST
> premido	premir+V+PTPST
> provindo	provir+V+PTPST
> reconvindo	reconvir+V+PTPST
> revindo	revir+V+PTPST
> ringido	ringir+V+PTPST
> sobrevindo	sobrevir+V+PTPST
> vindo	vir+V+PTPST
>  

A maioria esmagadora dos verbos não possui essa forma redundante. Compare:

`grep -Ph "\t.+PTPST$" verbs-a*.dict | wc -l`

> 20

`grep -Ph "\t.+PTPST\+M\+SG" verbs-a*.dict | wc -l`

> 34648

Antes de eliminar essas entradas espúrias, porém, é importante verificar se existem as formas correspondentes marcadas com _+M+SG_. Para pelo menos quatro desses verbos, a resposta é positiva:

`grep -Ph "\t(ringir|fritar|advir|frangir)\+V\+PTPST\+M\+SG" verbs-a*.dict`

> advindo	advir+V+PTPST+M+SG
> frangida	frangir+V+PTPST+M+SG
> frangidas	frangir+V+PTPST+M+SG
> frangido	frangir+V+PTPST+M+SG
> frangidos	frangir+V+PTPST+M+SG
> frita	fritar+V+PTPST+M+SG
> fritado	fritar+V+PTPST+M+SG
> fritas	fritar+V+PTPST+M+SG
> frito	fritar+V+PTPST+M+SG
> fritos	fritar+V+PTPST+M+SG
> ringida	ringir+V+PTPST+M+SG
> ringidas	ringir+V+PTPST+M+SG
> ringido	ringir+V+PTPST+M+SG
> ringidos	ringir+V+PTPST+M+SG

É interessante que, com exceção de _advir_, esses verbos também apresentam formas espúrias de masculino singular que não terminam em _o_.

**Comment by analununes** [comment]
> Terminação 	Etiquetas
> o 	PTPST+M+SG
> a 	PTPST+F+SG
> os 	PTPST+M+PL
> as 	PTPST+F+PL

Exceto as formas [assente/assentes](http://www.portaldalinguaportuguesa.org/simplesearch.php?action=lemma&lemma=24481&highlight=^assente$), [empregue/empregues](http://www.portaldalinguaportuguesa.org/simplesearch.php?action=lemma&lemma=41084&highlight=^empregue$) e [entregue/entregues](http://www.portaldalinguaportuguesa.org/simplesearch.php?action=lemma&lemma=105439&highlight=^entregue$), todas as entradas que não seguiam o padrão citado acima e as entradas sem marcação de gênero e número foram eliminadas no commit 3fd6813fcfaa473f778d7fd1ce945299ceb5dc44.
