### ISSUE TITLE
Chassis SG and PL?

### ISSUE THREAD

**Issue by wellington36** [LR-POR/MorphoBr#101]
Atualmente no MorphoBr temos:

```
chassis	chassi+N+M+PL
chassi	chassi+N+M+SG
```
Mas em [dicio.com.br](https://duvidas.dicio.com.br/chassis-ou-chassi/) fala que "a palavra chassis pode ser usada para indicar o singular ou o plural".

**Comment by leoalenc** [comment]
@wellington36, o [Dicionário da Editora Porto](https://www.infopedia.pt/dicionarios/lingua-portuguesa/chassi), a principal referência em se tratando do português europeu, apresenta _chassis_, nome masculino de dois números, como variante de _chassi_. No entanto, o Aulete, uma das referências mais tradicionais para o português do Brasil, consigna apenas _chassi_. Não posso consultar agora as minhas versões impressas do Aurélio e do Houaiss, as duas outras referências fundamentais, a respeito. 
Seja como for, como o MorphoBr deve contemplar as duas variedades da língua, devemos ter:

> chassis	chassi+N+M+PL
> chassi	chassi+N+M+SG
> 
> chassis	chassis+N+M+PL
> chassis	chassis+N+M+SG

No formato simplificado, as duas últimas resultam numa única entrada:

 > chassis	chassis+N+M

**Comment by leoalenc** [comment]
@wellington36, o Portal da Língua Portuguesa também consigna _chassi_ e _chassis_:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=104812
http://www.portaldalinguaportuguesa.org/simplesearch.php?action=lemma&lemma=79303&highlight=^chassis$

 Aproveito para chamar atenção para o[ Portal da Língua Portuguesa](http://www.portaldalinguaportuguesa.org/main.html), "um repositório organizado de recursos linguísticos" desenvolvido pelo Instituto de Linguística Teórica e Computacional (ILTEC) da Universidade de Lisboa, que deve ser uma fonte constante de consulta para todo interessado no léxico do português.

**Comment by analununes** [comment]
A entrada `chassis chassis+N+M` foi adicionada em f97fa53f1c1821c612f764177eaa76d5c3de00ba.
