### ISSUE TITLE
formas espúrias de verbos com alternância no radical

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#102]
@arademaker, continuando a utilizar o MorphoBr para testar a PorGram, descobri novos erros. De início, pensei que refazer a conjugação portuguesa na gramática seria um retrabalho que seria melhor evitar. No entanto, vejo agora que está sendo uma oportunidade de verificar a boa formação morfológica de entradas do MorphoBr. Aparentemente, essas entradas foram construídas por procedimentos automáticos que se têm revelado errôneos em muitos casos.  
Esta questão foca os verbos da terceira conjugação do tipo de _ferir_ e _vestir_ que sofrem alternância vocálica na primeira pessoa do singular do presente do indicativo e em todo o presente do subjuntivo, bem como nas formas derivadas do imperativo:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=39760
http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=20398

 Contabilizo 71 desses verbos:

`~/MorphoBr/verbs$ grep -Ph ".+i([bcdfghjlmnprstvxz])o\t.+e\1ir\+V\+PRS\+1\+SG" verbs-a*.dict | wc -l`
>71

No entanto, alguns dos verbos que se enquadram no padrão de _ferir_ e _vestir_ não apresentam a alternância no MorphoBr:

`~/MorphoBr/verbs$ grep -Ph ".+e([bcdfghjlmnprstvxz])o\t.+e\1ir\+V\+PRS\+1\+SG" verbs-a*.dict `

> defero	deferir+V+PRS+1+SG
> desmedo	desmedir+V+PRS+1+SG
> despreveno	desprevenir+V+PRS+1+SG
> enjero	enjerir+V+PRS+1+SG
> espedo	espedir+V+PRS+1+SG
> estreso	estresir+V+PRS+1+SG
> freteno	fretenir+V+PRS+1+SG
> inquero	inquerir+V+PRS+1+SG
> profero	proferir+V+PRS+1+SG
> remo	remir+V+PRS+1+SG
> zeno	zenir+V+PRS+1+SG
>  
 
Dessas entradas, apenas a última está correta, pois o verbo _zenir_ constitui uma exceção à regra de alternância _e->i_:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=12267

Segundo o Portal da Língua Portuguesa, os verbos _esmerir_, _fretenir_ e _remir_ são defectivos, carecendo das formas rizotônicas, embora esse recurso pareça incorrer em contradição ao apresentar formas rizotônicas de _fretenir_ no imperativo correspondentes a formas do subjuntivo:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=68518

As outras entradas estão erradas: os verbos ou sofrem alternância vocálica (_eu profiro_) ou seguem o modelo de _medir_ (por exemplo, _eu desmeço_), que sofre alternância de consoante do radical:

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=6500
http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=23215

Desse modo, correções precisam ser feitas não apenas nas entradas transcritas, mas também nas outras entradas sujeitas a alternância no radical.

**Comment by arademaker** [comment]
related #106

**Comment by analununes** [comment]
Resolvido no commit 4d905b2f9ba61f8576bed0e0095007cb6e5cccaa.
