### ISSUE TITLE
verbos no infinitivo que não terminam em (ar|er|ir|em|es|os)

### ISSUE THREAD

**Issue by analununes** [LR-POR/MorphoBr#103]
Alguns verbos no infinitivo estão errados.
O comando `grep V+INF ./* | egrep -v '.*(ar|er|ir|es|em|os)[[:space:]]'` retorna os verbos que não seguem as regras para infinitivo.
@leoalenc @arademaker 
```
./verbs-aaa.dict:ababadarde	ababadar+V+INF+2+PL
./verbs-aaa.dict:ababadare	ababadar+V+INF+2+SG
./verbs-aaa.dict:ababadarmo	ababadar+V+INF+1+PL
./verbs-aaa.dict:ababadá	ababadar+V+INF
./verbs-aaa.dict:ababadá	ababadar+V+INF+1+SG
./verbs-aaa.dict:ababadá	ababadar+V+INF+3+SG
./verbs-aaa.dict:ababalharde	ababalhar+V+INF+2+PL
./verbs-aaa.dict:ababalhare	ababalhar+V+INF+2+SG
./verbs-aaa.dict:ababalharmo	ababalhar+V+INF+1+PL
./verbs-aaa.dict:ababalhá	ababalhar+V+INF
./verbs-aaa.dict:ababalhá	ababalhar+V+INF+1+SG
./verbs-aaa.dict:ababalhá	ababalhar+V+INF+3+SG
./verbs-aaa.dict:ababelarde	ababelar+V+INF+2+PL
./verbs-aaa.dict:ababelare	ababelar+V+INF+2+SG
./verbs-aaa.dict:ababelarmo	ababelar+V+INF+1+PL
./verbs-aaa.dict:ababelá	ababelar+V+INF
./verbs-aaa.dict:ababelá	ababelar+V+INF+1+SG
./verbs-aaa.dict:ababelá	ababelar+V+INF+3+SG
./verbs-aaa.dict:ababosarde	ababosar+V+INF+2+PL
./verbs-aaa.dict:ababosare	ababosar+V+INF+2+SG
```

**Comment by leoalenc** [comment]
@analununes e @arademaker, esta _issue_ constitui um caso específico de #104. Todas essas formas resultam da elisão de _r_ e _s_ finais quando da adjunção de determinados pronomes enclíticos, como, por exemplo, _o_, _a_, _os_ e _as_, que assumem as formas _lo_, _la_ etc., dependendo das terminação verbal. Essas formas, como sabemos, estão no diretório _clitics_.

**Comment by arademaker** [comment]
As regras que @leoalenc detalhou na issue #104 cobrem os casos desta issue?

**Comment by leoalenc** [comment]
> As regras que @leoalenc detalhou na issue #104 cobrem os casos desta issue?
> 
> Ou somam-se a descrição do Leonel no comentário acima?

@arademaker e @analununes, cobrem sim, é por isso que comentei que #103 constitui caso particular de #104, partindo do pressuposto de que as formas descritas  [na regra 2](https://github.com/LR-POR/MorphoBr/issues/104#issuecomment-890363872) de #104  são duplicatas espúrias de formas corretas com _s_. Seria bom, contudo, verificar se não há dessas formas espúrias sem as correspondentes formas corretas.
Na conjugação do português, a segunda pessoa do singular sofre queda de _s_ final nos seguintes casos, ao se contrair com determinados clíticos:

> comprava comprar+V+IMPF+2+SG
> comprara comprar+V+PQP+2+SG
> comprare comprar+V+INF+2+SG

Fiz as seguintes contagens:

Formas sem _s_ final:

`~/MorphoBr/verbs$ awk '$1 !~ /s$/ && $2 ~ /(IMPF|PQP|INF)\+2\+SG/' verbs-a*.dict | wc -l`
>45106

Formas com _s_ final:
`~/MorphoBr/verbs$ awk '$1 ~ /s$/ && $2 ~ /(IMPF|PQP|INF)\+2\+SG/' verbs-a*.dict | wc -l`
>84199

Os números discrepam. Portanto, é importante verificar se cada forma espúria tem a correspondente forma gramatical.

**Comment by analununes** [comment]
O problema dessa issue foi tratado em #104.
