### ISSUE TITLE
INFL-INF-2SG não terminando em "res"

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#110]
@analununes, mais um exemplo na tabela de um tipo que destaquei em #106:
  
> assentares	INFL-INF-2SG-SUFFIX	assentar
> assenta	INFL-INF-2SG-SUFFIX	assentar **erro**

Verificar todo o MorphoBr se não há outros desses pares e eliminar as formas espúrias.

**Comment by analununes** [comment]
Resolvido no commit 8c2b51702bdb1ae6ea9804b055386cb36deee0ae.
