### ISSUE TITLE
PAST-PART de	"assentar" indicando problema do algoritmo de classificação?

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#111]
@analununes, http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=24481 não apresenta _assento_ para PAST-PART. Na tabela _irregs.txt_, temos: 
 
> assentado	PAST-PART-SUFFIX	assentar
> assente	PAST-PART-SUFFIX	assentar
> assentado	PAST-PART-SUFFIX	assentar
> assento	PAST-PART-SUFFIX	assentar

Estou estranhando a repetição de _assentado_. Isso não deveria ocorrer, mesmo se admitirmos que _assento_ é um particípio válido. Problema de desenho do algoritmo?

**Comment by analununes** [comment]
As entradas _assento_ e _assentos_ foram eliminadas no commit 3fd6813fcfaa473f778d7fd1ce945299ceb5dc44. A questão da duplicação será tratada [aqui](https://github.com/LR-POR/tools/issues/10).

**Comment by arademaker** [comment]
mas vc não respondeu a pergunta do @leoalenc , era um problema no algoritmo?

**Comment by analununes** [comment]
> mas vc não respondeu a pergunta do @leoalenc , era um problema no algoritmo?

@arademaker, para cada forma, o algoritmo classifica como regular ou irregular e produz a saída correspondente. No caso acima, quando _assente_ foi analisado a saída produzida foi:


> assentado PAST-PART-SUFFIX assentar
> assente PAST-PART-SUFFIX assentar
 
que corresponde à forma regular e à forma regular e individualmente está certo.

A saída produzida para a forma _assento_ também está individualmente certa, forma regular e forma irregular:

> assentado PAST-PART-SUFFIX assentar
> assento PAST-PART-SUFFIX assentar

O problema é que a entrada regular `assentado PAST-PART-SUFFIX assentar` deveria ocorrer apenas uma vez na tabela, ou seja, as duas saídas juntas deveriam ser:

> assentado PAST-PART-SUFFIX assentar
> assente PAST-PART-SUFFIX assentar
> assento PAST-PART-SUFFIX assentar

**Comment by leoalenc** [comment]
> 
> O problema é que a entrada regular `assentado PAST-PART-SUFFIX assentar` deveria ocorrer apenas uma vez na tabela, ou seja, as duas saídas juntas deveriam ser:
> 
> > assentado PAST-PART-SUFFIX assentar
> > assente PAST-PART-SUFFIX assentar
> > assento PAST-PART-SUFFIX assentar

@arademaker e @analununes , sim, deveria ser dessa forma.
