### ISSUE TITLE
participles with enclitic pronouns

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#118]
@arademaker e @leoalenc, nos clíticos ainda existe a tag `PTPASS`, vamos atualizar?

```
provindo-a	provir+V.ele.ACC.3.F.SG+PTPASS
provindo-as	provir+V.ele.ACC.3.F.PL+GRD
provindo-as	provir+V.ele.ACC.3.F.PL+PTPASS
```

_Originally posted by @analununes in https://github.com/LR-POR/MorphoBr/issues/81#issuecomment-959770550_

**Comment by leoalenc** [comment]
@analununes, em nenhuma variedade do português, ocorre naturalmente formas de particípio passado (ou passivo) com pronome enclítico:

>O João tinha-a comprado. (português europeu)
>O João a tinha comprado. (forma preferida no português brasileiro)
>O João tinha comprado ela. (português brasileiro coloquial)
>*O João tinha comprado-a. (ocorre eventualmente por hipercorreção)

Desse modo, entradas como

>provindo-a	provir+V.ele.ACC.3.F.SG+PTPASS
>provindo-as	provir+V.ele.ACC.3.F.PL+PTPASS

devem ser eliminadas. Suspeito que se trate de erro de um algoritmo de geração de formas, uma vez que esses particípios com enclíticos são homônimos das formas de gerúndio.  Essa identidade de formas é uma característica dos verbos derivados de *vir*.

**Comment by analununes** [comment]
> @analununes, em nenhuma variedade do português, ocorre naturalmente formas de particípio passado (ou passivo) com pronome enclítico:
> 
> > O João tinha-a comprado. (português europeu)
> > O João a tinha comprado. (forma preferida no português brasileiro)
> > O João tinha comprado ela. (português brasileiro coloquial)
> > *O João tinha comprado-a. (ocorre eventualmente por hipercorreção)
> 
> Desse modo, entradas como
> 
> > provindo-a	provir+V.ele.ACC.3.F.SG+PTPASS
> > provindo-as	provir+V.ele.ACC.3.F.PL+PTPASS
> 
> devem ser eliminadas. Suspeito que se trate de erro de um algoritmo de geração de formas, uma vez que esses particípios com enclíticos são homônimos das formas de gerúndio. Essa identidade de formas é uma característica dos verbos derivados de _vir_.

@leoalenc, entendi! Vou eliminar essas entradas!

**Comment by analununes** [comment]
@arademaker  e @leoalenc, no commit 077f617ebae89a1c8b3cb367212eb077bc7279d9 eliminei as entradas com a tag `PTPASS`, no total foram 165 entradas eliminadas com a função [delclitics](https://github.com/LR-POR/tools/commit/09113d1bf904327ed16536da7641b42183263e6b):

[ptpass.txt](https://github.com/LR-POR/MorphoBr/files/7488724/ptpass.txt)

@arademaker, o diff dos arquivos está disponível!!

**Comment by arademaker** [comment]
> @analununes, em nenhuma variedade do português, ocorre naturalmente formas de particípio passado (ou passivo) com pronome enclítico:
> 1. O João tinha-a comprado. (português europeu)
> 2. O João a tinha comprado. (forma preferida no português brasileiro)
> 3. O João tinha comprado ela. (português brasileiro coloquial)
> 4. *O João tinha comprado-a. (ocorre eventualmente por hipercorreção)

Eu não entendi os exemplos @leoalenc , se estas formas não são do pronome, como seriam analisadas?

**Comment by leoalenc** [comment]
> > @analununes, em nenhuma variedade do português, ocorre naturalmente formas de particípio passado (ou passivo) com pronome enclítico:
> > 
> > 1. O João tinha-a comprado. (português europeu)
> > 2. O João a tinha comprado. (forma preferida no português brasileiro)
> > 3. O João tinha comprado ela. (português brasileiro coloquial)
> > 4. *O João tinha comprado-a. (ocorre eventualmente por hipercorreção)
> 
> Eu não entendi os exemplos @leoalenc , se estas formas não são do pronome, como seriam analisadas?

@arademaker , não endendi sua dúvida. São formas do pronome átono acusativo de terceira pessoa do singular, o que eu disse foi que não se adjungem em ênclise com o particípio passado (ou passivo), restrição que vale para qualquer outro clítico pronominal do português.
