### ISSUE TITLE
adicionar formas do verbo aspergir

### ISSUE THREAD

**Issue by analununes** [LR-POR/MorphoBr#120]
> 
> @leoalenc, as formas geradas pelas regras não foram as esperadas:
> 
> 
> aspirga	aspergir+V+SBJR+1+SG
> aspirga	aspergir+V+SBJR+3+SG
> aspirgais	aspergir+V+SBJR+2+PL
> aspirgam	aspergir+V+SBJR+3+PL
> aspirgamos	aspergir+V+SBJR+1+PL
> aspirgas	aspergir+V+SBJR+2+SG
> aspirgo	aspergir+V+PRS+1+SG
>

@analununes, obrigado. De fato, esse verbo é irregular, apresentando variações no radical não contempladas pelas regras de _my-irules.tdl_. Você pode fazer as inclusões devidas seguindo o paradigma abaixo?

http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=1990

Veja que formas como *eu aspirjo* constam da conjugação do verbo *aspergir* segundo alguns sites:

https://www.conjugacao-de-verbos.com/verbo/aspergir.php

https://estraviz.org/conjugar.php?palavra=aspergir

Não sei se o primeiro é confiável, e o segundo é, na verdade, um dicionário da língua galega. 
No momento, temos:

`awk '$3 ~ /^aspergir$/ {print $1,$2,$3}' irregs.txt` 

> aspirjo PRES-IND-1SG-SUFFIX aspergir
> aspirjas PRES-SUBJ-2SG-SUFFIX aspergir
> aspirjamos PRES-SUBJ-1PL-SUFFIX aspergir
> aspirjam PRES-SUBJ-3PL-SUFFIX aspergir
> aspirjais PRES-SUBJ-2PL-SUFFIX aspergir
> aspirja PRES-SUBJ-1SG-SUFFIX aspergir
> aspirja PRES-SUBJ-3SG-SUFFIX aspergir
> 

Cunha e Cintra (1985, p. 409) não abonam essas formas com *i*, mas prefiro deixá-las, pois podem ocorrer dialetalmente.

_Originally posted by @leoalenc in https://github.com/LR-POR/MorphoBr/issues/106#issuecomment-947701002_

**Comment by analununes** [comment]
Das entradas produzidas (manualmente), usando como referência http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=1990, as entradas abaixo são as únicas que ainda não foram incluídas no MorphoBr: 

```
asperjais	aspergir+V+IMP+2+PL
asperjas	aspergir+V+IMP+2+SG
aspersa	aspergir+V+PTPST+F+SG
aspersas	aspergir+V+PTPST+F+PL
asperso	aspergir+V+PTPST+M+SG
aspersos	aspergir+V+PTPST+M+PL

```
@leoalenc, as informações morfológicas estão corretas? Essas entradas podem ser adicionadas no MorphoBr?

**Comment by leoalenc** [comment]
> Das entradas produzidas (manualmente), usando como referência http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=1990, as entradas abaixo são as únicas que ainda não foram incluídas no MorphoBr:
> 
> ```

> aspersa	aspergir+V+PTPST+F+SG
> aspersas	aspergir+V+PTPST+F+PL
> asperso	aspergir+V+PTPST+M+SG
> aspersos	aspergir+V+PTPST+M+PL
> ```
> 
> @leoalenc, as informações morfológicas estão corretas? Essas entradas podem ser adicionadas no MorphoBr?

@analununes , acho redundante incluir as formas desse chamado imperativo negativo, uma vez que são idênticas às do subjuntivo presente. Portanto, talvez seja o caso de não incluir estas formas:

> asperjais	aspergir+V+IMP+2+PL
> asperjas	aspergir+V+IMP+2+SG

Pode verificar como isso está sendo tratado no MorphoBr e, eventualmente, abrir *issue* a respeito? Penso que não deveríamos ter formas de segunda pessoa do imperativo terminadas em *s*, por conta desse chamado *imperativo negativo*. Enfim, o MorphoBr não deveria ter esse  *imperativo negativo*, uma redundância da gramática tradicional.

**Comment by analununes** [comment]
@leoalenc, entendi, criei a issue #124 para tratar disso.

**Comment by analununes** [comment]
Resolvido em c258af2946a644acb947793a51d84d49a80d0f10.
