### ISSUE TITLE
incorrect form of the verb "ter"

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#127]
Ao aplicar a PorGram sobre um exemplo com a forma *tive* do verbo *ter*, obtive duas análises que diferem apenas na pessoa da forma, uma na primeira e a outra, na terceira do singular. No entanto, essa forma é apenas primeira do singular, ver, por exemplo, [aqui](http://www.portaldalinguaportuguesa.org/simplesearch.php?action=lemma&lemma=61892&highlight=^ter$). 
No arquivo `my-irregs.tab` da gramática, gerado com base no MorphoBr, temos:

> **tive PERF-IND-1SG-SUFFIX ter** (FORMA ESPÚRIA)
> tiveram PERF-IND-3PL-SUFFIX ter
> tiveste PERF-IND-2SG-SUFFIX ter
> tivestes PERF-IND-2PL-SUFFIX ter
> **tive PERF-IND-1SG-SUFFIX ter**

No MorphoBr, encontramos a razão para o erro:

`~/MorphoBr/verbs$ awk '$2 ~ /^ter\+V\+/' *.dict`

> [...]
> teve	ter+V+PRF+3+SG
> [...]
> **tive	ter+V+PRF+3+SG** (FORMA ESPÚRIA)
> tive	ter+V+PRF+1+SG
> [...]

@arademaker, temos no momento diversos ramos do MorphoBr, estou confuso a respeito de onde devo efetuar a correção.

**Comment by arademaker** [comment]
The commit a39a729 solves this issue in the master branch.
