### ISSUE TITLE
verbos defectivos

### ISSUE THREAD

**Issue by arademaker** [LR-POR/MorphoBr#128]
https://www.conjugacao.com.br/verbos-defectivos/

Colorir está no morphobr.

**Comment by leoalenc** [comment]
> https://www.conjugacao.com.br/verbos-defectivos/
> 
> Colorir está no morphobr.

@arademaker, creio que já discutimos isso lá nos idos de 2018. É preciso ficar sempre com pé atrás pra esses sites de professores de português. Frequentemente, fornecem informações úteis. No entanto, o foco é o público em geral, que busca fazer consultas atendendo a demandas alheias ao processamento de linguagem natural e à modelagem matemática da língua. Esses consulentes visam estudar para concursos, realizar tarefas de português da escola… A base todo esse sistema é a gramática tradicional, cujo estatuto científico está para linguística formal, por exemplo, de base gerativa, como a física dos gregos antigos (o átomo como unidade indivisível da matéria) para física contemporânea (estrutura interna do átomo constituída de nêutrons, prótons e elétrons).
Sob a perspectiva da 
língua enquanto sistema cognitivo, ou seja, o conjunto de conhecimentos sobre o sistema linguístico de um indivíduo, denominado competência por Chomsky, cuja modelagem matemática/computacional é o objetivo da linguística gerativa, qual é o estatuto dos verbos chamados defectivos? São verbos que possuem formas que não são realizadas por questões de performance?
E é uma questão não trivial de linguística. Eu tendo a crer que a competência linguística possui regras que geram as formas dos verbos defectivos, mas que, por razões de ordem pragmática ou pelo simples fato de que a gramática tradicional as proíbe, essas formas não são geralmente usadas.
Desse modo, concluo que não vale a pena excluir essas formas e existem questões do nosso recurso que seriam mais proveitosas para o seus alunos.

**Comment by arademaker** [comment]
certamente pode ser necessário marcar de alguma forma as palavras possíveis as palavras realizadas... como já falamos antes. Talvez tomando como referência, alguns corpora. Mas vou então fechar este issue por agora.
