### ISSUE TITLE
organização dos arquivos

### ISSUE THREAD

**Issue by odanoburu** [LR-POR/MorphoBr#2]
usar o comando `split` é uma boa ideia pra diminuir o tamanho dos arquivos-dicionário e balancear o tamanho deles, mas me parece ter uma desvantagem: ao adicionarmos novas palavras e rerodarmos o comando, vamos ter palavras saindo de um arquivo para outro, o que vai aumentar o `diff` desnecessariamente. depois de muitas iterações disso, pode até ser que o repositório fique com um tamanho excessivo (o que vai dificultar a clonagem por quem for usá-lo).

minha ideia era separar as entradas por índice (algo como  a-j, k-n, etc), o que possivelmente vai demandar um script. isso pode criar um desbalanceamento no tamanho dos arquivos, mas acredito que a distribuição das entradas não deva mudar muito agora que já temos muitas delas.

o que acham?

**Comment by odanoburu** [comment]
outra opção seria separar só nas classes mesmo (nouns, verbs, verbs-clitcs, etc.), e quem precisasse de arquivos menores (para facilitar o processamento, talvez) poderia usar o comando `split` individualmente

**Comment by arademaker** [comment]
@odanoburu a segunda opção, do comentário anterior, também irá gerar alterações nos arquivos desnecessárias. Uma única mudança de um verbo irá gerar uma nova versão do arquivo verb. Acho que a idéia de separar em blocos a-j, k-n etc me parece melhor. E não se trata apenas do tamanho dos diffs. O ideal aqui é melhor acompanhamentos das mudanças em cada arquivo. Tamanho também é relevante para tornar o arquivo visualizável na interface web do github.

**Comment by arademaker** [comment]
Se todos concordarem com o split controlado, por iniciais, o comando split pode ser usado facilmente, vi agora a opção `-p` do split do MacOS. Bastaria juntarmos tudo, marcarmos os pontos de corte com algum padrão como `---` e usar o split.

**Comment by leoalenc** [comment]
Em princípio,  Pode ser como vocês acharem melhor! Vou só mostrar o ponto de vista de quem precisa compilar os recursos em máquinas de estados finitos utilizando o pacote de estados finitos da xerox ou seu clone Software Livre foma:  esse processo pode estourar a memória quando o arquivo de entrada tem um número excessivo de linhas, não me lembro bem o número exato, mas acho que a partir de 100.000 linhas já temos problema.  Quebrando o arquivo em blocos de até 20.000 linhas,  ou talvez até menos, eu precisaria verificar,  é fácil por meio de script  construir várias máquinas e depois realizar união entre elas.  Com relação à  separação, eu sou favorável a manter as classes de palavras separadas,  porque temos uma grande descompensação de tamanho entre elas, no meu computador que só tem dois giga bytes de memória,  alguns operações de extração de  palavras e divisão em arquivos demorou muito tempo.  Quem Trabalha com morfologia vai precisar trabalhar com classes separadamente .  Por exemplo, agora eu vou precisar dos substantivos masculinos e dos substantivos femininos para formar diminutivos, seria muito trabalho mais trabalhoso extrair isso de um grande arquivo incluindo os verbos.  Desse modo, sugiro: separação por classes de palavras e, dentro dessas, por blocos que podem estar organizados alfabeticamente.  Não vejo necessidade de marcar um ponto de corte, porque cada linha é independente da outra.

**Comment by leoalenc** [comment]
Desculpe se eu entendi mal a questão do ponto de corte, vejo agora que esse é o lugar onde vai ser feito o corte.

**Comment by leoalenc** [comment]
Mas podemos esperar pra fazer isso depois que eu preparar uma nova versão dos verbos com clíticos? Cheguei à  conclusão de que é importante incluir a forma canônica dos pronomes.

**Comment by odanoburu** [comment]
> esse processo pode estourar a memória quando o arquivo de entrada tem um número excessivo de linhas, não me lembro bem o número exato, mas acho que a partir de 100.000 linhas já temos problema.

também tenho esses problemas de hardware! mas nesse caso nós podemos usar o comando split sempre que precisarmos, e ficar com o melhor formato para distribuição!

> Mas podemos esperar pra fazer isso depois que eu preparar uma nova versão dos verbos com clíticos? Cheguei à conclusão de que é importante incluir a forma canônica dos pronomes.

@leoalenc podemos esperar sim! qual mudança vc propõe?

**Comment by leoalenc** [comment]
Então está certo, fica no formato que vocês acharem melhor  para distribuição.  Vou incluir as modificações daqui a pouco.

**Comment by fcbr** [comment]
Pra mim `.dic` or `.dict` esta' bem.  Me preocupo mais em ter uma extensao consistente do que o valor especificamente escolhido.

Em relacao ao split, meu unico comentario e termos uma coisa consistente e uniforme entre os tipos.  Nao acho que uma forma ou outra de split e' melhor ou pior a prior, depende de como o projeto for evoluir...

**Comment by arademaker** [comment]
Meu racional expliquei no comentário https://github.com/LFG-PTBR/MorphoBr/pull/33#issue-182473873. Mas o fundamental mesmo agora é adotarmos uma extensão padrão para todos os arquivos de dados. No médio prazo, precisamos organizar os nomes também para melhor refletir a origem dos conteúdos de cada arquivo , mas dependendo de como evoluirmos, pode ficar complicado tentar manter esta `provenance` dos dados.

**Comment by leoalenc** [comment]
@odanoburu   Acho que a ideia de acrescentar uma primeira coluna com a sigla indicando a origem dos dados muito boa!   Assim, teríamos apenas um tipo de arquivo, com uma mesma extensão, quebrado em arquivos menores pelo critério alfabético. Para entradas geradas pelo componente de estados finitos, poderíamos ter FST.  Nós precisamos de várias outras siglas para indicar aquelas coisas que incluímos manualmente por meio de ferramentas do unix etc.

**Comment by odanoburu** [comment]
@arademaker @leoalenc agora que descobri o comando `comm` fica bem mais fácil de lidar com os arquivos quando eles estão separados, então acho que não precisamos mais de seguir com essa ideia!

**Comment by leoalenc** [comment]
Ok

**Comment by arademaker** [comment]
@lucasrct, por favor, vamos conversar e resolver este issue depois/junto com o #59

**Comment by arademaker** [comment]
@analununes para sua leitura no contexto do issue #12. Vou fechar este issue porque vc já está adotando um critério de separação e este issue também já está antigo em relação a alterações ja aplicadas no repositório.
