### ISSUE TITLE
formas verbais inválidas GFL

### ISSUE THREAD

**Issue by arademaker** [LR-POR/MorphoBr#34]
pra eliminar as formas agramaticais do tipo

```
ababadamo       ababadar+V+PRF+1+PL
ababadamo       ababadar+V+PRS+1+PL
ababadáramo     ababadar+V+PQP+1+PL
ababadarmo      ababadar+V+SBJF+1+PL
ababadarmo      ababadar+V+INF+1+PL
ababadássemo    ababadar+V+SBJP+1+PL
ababadávamo     ababadar+V+IMPF+1+PL
ababademo       ababadar+V+SBJR+1+PL
```

basta executar

```
grep -Ev ".*mo[[:space:]].*\+V\+[A-Z]+\+1\+PL" x*.pairs > verbs.pairs
```

existem certamente outras formas agramaticais no GLF decorrentes da estratégia de toquenização adotada. o número de casos é limitado. eu poderia fazer esse levantamento, mas se alguém criativo quiser bolar um programinha pra fazer isso, melhor. estratégia: checar se a forma adicional equivale à forma que se obtém separando o clítico da forma com V+PRO no DELAF-PB. Caso afirmativo, deletar a forma adicional.
Por exemplo, dado

```
ababadávamo     ababadar+V+IMPF+1+PL
ababadávamos     ababadar+V+IMPF+1+PL
```
checamos se uma dessas formas corresponde ao que obtemos separando as formas de ababadar+V+IMPF+1+PL com clítico, ou seja

```
grep -Eh "ababadar\+V.*\+IMPF\+1\+PL" uniq.*.pairs
ababadávamo-la  ababadar+V.ele.ACC.3.F.SG+IMPF+1+PL
ababadávamo-las ababadar+V.ele.ACC.3.F.PL+IMPF+1+PL
ababadávamo-lo  ababadar+V.ele.ACC.3.M.SG+IMPF+1+PL
ababadávamo-los ababadar+V.ele.ACC.3.M.PL+IMPF+1+PL
ababadávamos-lhe        ababadar+V.ele.DAT.3.SG+IMPF+1+PL
ababadávamos-lhes       ababadar+V.ele.DAT.3.PL+IMPF+1+PL
ababadávamos-me ababadar+V.eu.AD.1.SG+IMPF+1+PL
ababadávamos-te ababadar+V.tu.AD.2.SG+IMPF+1+PL
ababadávamos-vos        ababadar+V.vós.AD.2.PL+IMPF+1+PL
```

o teste vai ser positivo porque separando e eliminado informação sobre clítico em

```
ababadávamo-la  ababadar+V.ele.ACC.3.F.SG+IMPF+1+PL
```

obtemos

```
ababadávamo ababadar+V+IMPF+1+PL
```

acredito que isso funciona pros verbos do GLF que estão do DELAF-PB. para os outros verbos, aí precisaríamos estender a estratégia, mas pensamos nisso depois. seria importante colecionar os casos de divergência encontrados na execução do algoritmo sugerido (por ex. IMPF+1+PL), creio que isso possa ser útil pra lidar com os verbos "desconhecidos".
eu poderia tranquilamente implementar esse algoritmo em Python, seria divertido, mas é melhor eu me concentrar no componente de estados finitos e no paper...

abraços
Leonel

**Comment by arademaker** [comment]
Estas 86K formas removidas são apenas nas formas que vieram do Garcia+Freeling. Vc tem como responder esta sua pergunta usando seu código GF, certo? Já temos uma forma rápida de fazer este check de 71 formas por verbo?

**Comment by odanoburu** [comment]
@arademaker  

> Já temos uma forma rápida de fazer este check de 71 formas por verbo?

sim, https://github.com/LFG-PTBR/MorphoBr/issues/22#issuecomment-381765701

**Comment by arademaker** [comment]
No grep do MacOS não está funcionando. O `-P` não roda então estou usando `-E` 

```
$ grep --color=never -o -E "\t[^+]+\+V" *pairs | sort | uniq -c > forms.count
$ grep -v "71" forms.count | wc -l
   15940
$ awk '{print $1}' forms.count  | sort | uniq -c 
 811 1
  13 10
   1 11
  17 12
   4 13
  12 14
   1 148
   4 15
   1 16
   2 17
   4 18
   2 19
12731 2
   1 21
   1 22
   2 23
   3 24
   9 25
   1 26
   1 27
   2 28
   4 29
   6 3
   1 30
   2 31
   1 32
   1 34
   1 36
   1 37
   1 39
   9 4
   1 40
   6 41
   2 42
   2 44
   2 45
   2 46
   7 47
   3 48
   1 49
   2 5
   1 50
   1 52
   3 53
   4 54
   1 55
   2 56
  11 57
   2 58
  17 59
   1 6
   1 60
  16 61
   4 62
   4 63
   2 64
   1 65
   2 66
   4 67
   7 68
1114 69
   2 7
 697 70
11991 71
 166 72
  42 73
  49 74
  81 75
   8 76
   2 79
   3 8
   4 81
   6 82
   4 9
```

Considerando também verbos do G+FL parece DOBRAR as tais formas incompletas:

```
$ grep --color=never -o -E "\t[^+]+\+V" *.{pairs,gfl} | sort | uniq -c > forms.count
$ grep -v "71" forms.count | wc -l
   31139
```

Aplicando o filtro do @leoalenc , temos MAIS verbos com número diferente de 71 formas! Estranho... Estou certo? Ta ficando complicado! ;-)

```
leme:verbs ar$ grep --color=never -Ev ".*mo[[:space:]].*\+V\+[A-Z]+\+1\+PL" verbs.diff.gfl > verbs.diff.gfl.filtrados
leme:verbs ar$ grep --color=never -o -E "\t[^+]+\+V" *.{pairs,filtrados} | sort | uniq -c > forms.count
leme:verbs ar$ grep -v "71" forms.count | wc -l
   31153
$ awk '{print $1}' forms.count  | sort | uniq -c
 812 1
  15 10
   3 11
   1 115
  18 12
   4 13
  47 14
   1 148
3203 15
 499 16
 303 17
1826 18
7370 19
12731 2
 688 20
  19 21
  70 22
  11 23
  44 24
  16 25
  15 26
  14 27
  25 28
  29 29
   6 3
  59 30
  12 31
   4 32
   3 34
   2 35
   3 36
   2 37
   2 38
   1 39
   9 4
   3 40
   6 41
   3 42
   2 44
   2 45
   2 46
   7 47
   3 48
   1 49
   2 5
   1 50
   1 51
   1 52
   3 53
   4 54
   1 55
   3 56
  11 57
   2 58
  18 59
   1 6
   1 60
  16 61
   4 62
   4 63
   2 64
   3 65
  20 66
   4 67
   7 68
1114 69
   3 7
 697 70
11993 71
 195 72
 198 73
  49 74
  81 75
   8 76
   1 78
   2 79
   5 8
  73 80
   7 81
  17 82
  86 83
 594 84
   1 85
   2 87
   1 88
   6 9
   1 90
   1 91
   1 96
   2 98
   3 99
```

**Comment by arademaker** [comment]
Se trocar os contadores por linhas do `forms.count` temos o número de verbos (lemas?):

```
$ sh check.sh
DELAS
   15940
359 15581 11991

DELAS + GFL
   31139
1328 29811 12007

DELAS + GFL - filter
1325 29828 11993
```

**Comment by odanoburu** [comment]
@arademaker vou fechar as outras issues relacionadas pra concentrarmos os esforços aqui, pode ser? #8 #22 #

**Comment by arademaker** [comment]
Issues #8 e #22 realmente são sobre DELAS apenas. Mas esta aqui envolve identificar o que pode ter vindo de 'lixo' de GFL.

**Comment by odanoburu** [comment]
uma forma de tirar alguns erros seria remover as duplicatas considerando duplicata oq tem lema+TAGS igual

assim tirariamos todos os verbos do tipo `falamo`

mas ainda ficariamos com os lemas estranhos, tipo `superior    alto`

**Comment by leoalenc** [comment]
@odanoburu me parece que a estratégia que você sugere eliminaria variantes legítimas como elegido e eleito

**Comment by odanoburu** [comment]
sim, de fato!

**Comment by leoalenc** [comment]
@arademaker Até agora, os casos espúrios de variantes paraa a mesma combinação de lemas e  etiquetas envolvem verbos que foram separados dos pronomes. Esses casos são bem conhecidos e bem descritos nas gramáticas do português. Além daquele programinha que eu sugeri, poderíamos, com base nessa descrição gramatical, elaborar vários filtros como aquele que eu propus,  procurando por comprá de comprá-lo etc.
 Existem, porém, casos legítimos de variantes, por exemplo aceitado e aceito.  No caso dos nomes, vários substantivos em -ão têm  vários plurais.  Por exemplo: aldeão – aldeões, aldeães, aldeãos.

**Comment by odanoburu** [comment]
@leoalenc vou colocar aqui algumas mudanças que pensei em fazer, me diga se elas fazem sentido por favor!

- remoção: terminação: `á` | tempo: infinitivo | comando:  `grep -v -P "á\t[^+]+ar\+V\+INF" verbs.uniq`  | arquivo: [verbs-inf.txt](https://github.com/LFG-PTBR/MorphoBr/files/1944435/verbs-inf.txt)

- remoção: terminação: `ava` | tempo:  PretI Ind Sg P2 | comando:  `grep -v -P "ava\t[^+]+\+V\+IMPF\+2\+SG" verbs.uniq`  | arquivo: 
[verbs-impf-2.txt](https://github.com/LFG-PTBR/MorphoBr/files/1944470/verbs-impf-2.txt)

- remoção: terminação: `mo` | tempo:  IMP+1+PL | comando:  `grep -v -P "mo\t[^+]+\+V\+IMP\+1\+PL" verbs.uniq`  | arquivo: [verbs-imp-1-pl.txt](https://github.com/LFG-PTBR/MorphoBr/files/1944595/verbs-imp-1-pl.txt)

- [vou adicionando mais aqui]

**Comment by arademaker** [comment]
@leoalenc disse no PR #45 

acho que as formas erroneamente formatadas com pronomes ligados aos verbos sem separação por hífen e que, simultaneamente, apresentam o erro de formatação objeto da issue #43 sumiram. 

grep -E "31" Delaf2015v04.dic > error31.dic
head !$
head error31.dic
abluir,abluir.V:W31
abluirlhe,abluir.V+PRO:W31
abluirlhes,abluir.V+PRO:W31
abluirme,abluir.V+PRO:W31
abluirnos,abluir.V+PRO:W31
abluirte,abluir.V+PRO:W31
abluirvos,abluir.V+PRO:W31
abnuir,abnuir.V:W31
abnuirlhe,abnuir.V+PRO:W31
abnuirlhes,abnuir.V+PRO:W31

Não consegui encontrar formas como, por exemplo, a seguinte:

abnuirlhe,abnuir.V+PRO:W31

@odanoburu vc pode checar isso?

**Comment by arademaker** [comment]
Este issue trata das formas verbais com pronomes que estavam sem hífen, certo? Precisamos fechar este issue antes do artigo.

**Comment by odanoburu** [comment]
```
Não consegui encontrar formas como, por exemplo, a seguinte:

abnuirlhe,abnuir.V+PRO:W31

@odanoburu vc pode checar isso?
```
@leoalenc a princípio eu acho ter corrigido todos os erros que apontei! desculpa não ter deixado isso claro, quando coloquei que o PR fechava as issues era por isso!

**Comment by arademaker** [comment]
Bem, para variar já estou perdido com tantas alterações em paralelo.. Me desculpem, não consigo acompanhar assim. Este issue pode ou não ser fechado?

**Comment by odanoburu** [comment]
não pode, @arademaker! esse último comentário que vc postou do Leonel era sobre erros no DELAF, e essa issue é sobre erros no GFL, certo? ainda não corrigimos todos esses erros..

**Comment by analununes** [comment]
O problema dessa issue foi tratado em #104.
