### ISSUE TITLE
typos in unpublished-garcia

### ISSUE THREAD

**Issue by odanoburu** [LR-POR/MorphoBr#51]
```
bentsa  benzer+V+PTPASS+F+SG
bentsas benzer+V+PTPASS+F+PL
bentso  benzer+V+PTPASS+M+SG
bentsos benzer+V+PTPASS+M+PL

gauuhada        gauchar+V+PTPASS+F+SG
gauuhadas       gauchar+V+PTPASS+F+PL
gauuhado        gauchar+V+PTPASS+M+SG
gauuhados       gauchar+V+PTPASS+M+PL
```

a origem desses erros está nos arquivos não-publicados pelo Marcos Garcia.

**Comment by arademaker** [comment]
Na verdade para benzer temos também outras formas iniciadas com `bent` que não aparecem em https://www.conjugacao.com.br/verbo-benzer/: 

```
33256benta	benzer+V+PTPST+F+SG
33257bentas	benzer+V+PTPST+F+PL
33258bento	benzer+V+PTPST+M+SG
33324bentos	benzer+V+PTPST+M+PL
33325bentsa	benzer+V+PTPST+F+SG
33326bentsas	benzer+V+PTPST+F+PL
33327bentso	benzer+V+PTPST+M+SG
33328bentsos	benzer+V+PTPST+M+PL
```

E para gauchar temos também algumas várias formas com duplo `uu` suspeitas que não aparecem em https://www.conjugacao.com.br/verbo-gauchar/. Imagino que estes erros podem ter sido introduzidos no recurso e propagados pelas regras de inflexão que implementamos:

```
4831 gauuhada	gauchar+V+PTPST+F+SG
4832 gauuhadas	gauchar+V+PTPST+F+PL
4833 gauuhado	gauchar+V+PTPST+M+SG
4834 gauuhados	gauchar+V+PTPST+M+PL
4835 gauuhai	gauchar+V+IMP+2+PL
4836 gauuhais	gauchar+V+PRS+2+PL
4837 gauuhamo	gauchar+V+PRF+1+PL
4838 gauuhamo	gauchar+V+PRS+1+PL
4839 gauuhamos	gauchar+V+PRF+1+PL
4840 gauuhamos	gauchar+V+PRS+1+PL
4841 gauuhando	gauchar+V+GRD
4842 gauuhar	gauchar+V+INF
4843 gauuhar	gauchar+V+INF+1+SG
4844 gauuhar	gauchar+V+INF+3+SG
4845 gauuhar	gauchar+V+SBJF+1+SG
4846 gauuhar	gauchar+V+SBJF+3+SG
4847 gauuhara	gauchar+V+PQP+1+SG
4848 gauuhara	gauchar+V+PQP+2+SG
4849 gauuhara	gauchar+V+PQP+3+SG
4850 gauuharam	gauchar+V+PQP+3+PL
4851 gauuharam	gauchar+V+PRF+3+PL
4852 gauuharas	gauchar+V+PQP+2+SG
4853 gauuharde	gauchar+V+INF+2+PL
4854 gauuhardes	gauchar+V+INF+2+PL
4855 gauuhardes	gauchar+V+SBJF+2+PL
4856 gauuhare	gauchar+V+INF+2+SG
4857 gauuharei	gauchar+V+FUT+1+SG
4858 gauuhareis	gauchar+V+FUT+2+PL
4859 gauuharem	gauchar+V+INF+3+PL
4860 gauuharem	gauchar+V+SBJF+3+PL
4861 gauuharemos	gauchar+V+FUT+1+PL
4862 gauuhares	gauchar+V+INF+2+SG
4863 gauuhares	gauchar+V+SBJF+2+SG
4864 gauuharia	gauchar+V+COND+1+SG
4865 gauuharia	gauchar+V+COND+3+SG
4866 gauuhariam	gauchar+V+COND+3+PL
4867 gauuharias	gauchar+V+COND+2+SG
4868 gauuharmo	gauchar+V+INF+1+PL
4869 gauuharmos	gauchar+V+INF+1+PL
4870 gauuharmos	gauchar+V+SBJF+1+PL
4871 gauuhará	gauchar+V+FUT+3+SG
4872 gauuharás	gauchar+V+FUT+2+SG
4873 gauuharão	gauchar+V+FUT+3+PL
4874 gauuharíamos	gauchar+V+COND+1+PL
4875 gauuharíeis	gauchar+V+COND+2+PL
4876 gauuhasse	gauchar+V+SBJP+1+SG
4877 gauuhasse	gauchar+V+SBJP+3+SG
4878 gauuhassem	gauchar+V+SBJP+3+PL
4879 gauuhasses	gauchar+V+SBJP+2+SG
4880 gauuhaste	gauchar+V+PRF+2+PL
4881 gauuhaste	gauchar+V+PRF+2+SG
4882 gauuhastes	gauchar+V+PRF+2+PL
4883 gauuhava	gauchar+V+IMPF+1+SG
4884 gauuhava	gauchar+V+IMPF+2+SG
4885 gauuhava	gauchar+V+IMPF+3+SG
4886 gauuhavam	gauchar+V+IMPF+3+PL
4887 gauuhavas	gauchar+V+IMPF+2+SG
4888 gauuhei	gauchar+V+PRF+1+SG
4889 gauuheis	gauchar+V+SBJR+2+PL
4890 gauuhemo	gauchar+V+IMP+1+PL
4891 gauuhemos	gauchar+V+IMP+1+PL
4892 gauuhemos	gauchar+V+SBJR+1+PL
4893 gauuhou	gauchar+V+PRF+3+SG
4894 gauuhá	gauchar+V+INF
4895 gauuhá	gauchar+V+INF+1+SG
4896 gauuhá	gauchar+V+INF+3+SG
4897 gauuháramo	gauchar+V+PQP+1+PL
4898 gauuháramos	gauchar+V+PQP+1+PL
4899 gauuhárei	gauchar+V+PQP+2+PL
4900 gauuháreis	gauchar+V+PQP+2+PL
4901 gauuhásseis	gauchar+V+SBJP+2+PL
4902 gauuhássemos	gauchar+V+SBJP+1+PL
4903 gauuhávamo	gauchar+V+IMPF+1+PL
4904 gauuhávamos	gauchar+V+IMPF+1+PL
4905 gauuhávei	gauchar+V+IMPF+2+PL
4906 gauuháveis	gauchar+V+IMPF+2+PL
4907 gauúha	gauchar+V+IMP+2+SG
4908 gauúha	gauchar+V+PRS+3+SG
4909 gauúham	gauchar+V+PRS+3+PL
4910 gauúhas	gauchar+V+PRS+2+SG
4911 gauúhe	gauchar+V+IMP+3+SG
4912 gauúhe	gauchar+V+SBJR+1+SG
4913 gauúhe	gauchar+V+SBJR+3+SG
4914 gauúhem	gauchar+V+IMP+3+PL
4915 gauúhem	gauchar+V+SBJR+3+PL
4916 gauúhes	gauchar+V+SBJR+2+SG
4917 gauúho	gauchar+V+PRS+1+SG
```

@leoalenc concorda em removermos estas entradas?

**Comment by leoalenc** [comment]
> Na verdade para benzer temos também outras formas iniciadas com `bent` que não aparecem em https://www.conjugacao.com.br/verbo-benzer/:
> 
> ```
> 33256benta	benzer+V+PTPST+F+SG
> 33257bentas	benzer+V+PTPST+F+PL
> 33258bento	benzer+V+PTPST+M+SG
> 33324bentos	benzer+V+PTPST+M+PL
> 33325bentsa	benzer+V+PTPST+F+SG
> 33326bentsas	benzer+V+PTPST+F+PL
> 33327bentso	benzer+V+PTPST+M+SG
> 33328bentsos	benzer+V+PTPST+M+PL
> ```
> 

@arademaker , em termos de conjugação e flexão, a referência mais confiável é esta, o Portal da Língua Portuguesa, do Instituto de Linguística Teórica e Computacional da Universidade de Lisboa: http://www.portaldalinguaportuguesa.org/simplesearch.php?action=lemma&lemma=3917&highlight=^bento$
 Existe, sim, o particípio _bento_ etc., ao lado de _benzido_. É um fenômeno mais geral da língua, ver, por exemplo, _ganho_ versus _ganhado_ etc. Por outro lado, inexistem as formas _bentso_ etc.

> E para gauchar temos também algumas várias formas com duplo `uu` suspeitas que não aparecem em https://www.conjugacao.com.br/verbo-gauchar/. Imagino que estes erros podem ter sido introduzidos no recurso e propagados pelas regras de inflexão que implementamos:
> 
> ```
> 4831 gauuhada	gauchar+V+PTPST+F+SG
> 4832 gauuhadas	gauchar+V+PTPST+F+PL
> 4833 gauuhado	gauchar+V+PTPST+M+SG
> 4834 gauuhados	gauchar+V+PTPST+M+PL
> 4835 gauuhai	gauchar+V+IMP+2+PL
> 4836 gauuhais	gauchar+V+PRS+2+PL
> 4837 gauuhamo	gauchar+V+PRF+1+PL
> 4838 gauuhamo	gauchar+V+PRS+1+PL
> 4839 gauuhamos	gauchar+V+PRF+1+PL
> 4840 gauuhamos	gauchar+V+PRS+1+PL
> 4841 gauuhando	gauchar+V+GRD
> 4842 gauuhar	gauchar+V+INF
> 4843 gauuhar	gauchar+V+INF+1+SG
> 4844 gauuhar	gauchar+V+INF+3+SG
> 4845 gauuhar	gauchar+V+SBJF+1+SG
> 4846 gauuhar	gauchar+V+SBJF+3+SG
> 4847 gauuhara	gauchar+V+PQP+1+SG
> 4848 gauuhara	gauchar+V+PQP+2+SG
> 4849 gauuhara	gauchar+V+PQP+3+SG
> 4850 gauuharam	gauchar+V+PQP+3+PL
> 4851 gauuharam	gauchar+V+PRF+3+PL
> 4852 gauuharas	gauchar+V+PQP+2+SG
> 4853 gauuharde	gauchar+V+INF+2+PL
> 4854 gauuhardes	gauchar+V+INF+2+PL
> 4855 gauuhardes	gauchar+V+SBJF+2+PL
> 4856 gauuhare	gauchar+V+INF+2+SG
> 4857 gauuharei	gauchar+V+FUT+1+SG
> 4858 gauuhareis	gauchar+V+FUT+2+PL
> 4859 gauuharem	gauchar+V+INF+3+PL
> 4860 gauuharem	gauchar+V+SBJF+3+PL
> 4861 gauuharemos	gauchar+V+FUT+1+PL
> 4862 gauuhares	gauchar+V+INF+2+SG
> 4863 gauuhares	gauchar+V+SBJF+2+SG
> 4864 gauuharia	gauchar+V+COND+1+SG
> 4865 gauuharia	gauchar+V+COND+3+SG
> 4866 gauuhariam	gauchar+V+COND+3+PL
> 4867 gauuharias	gauchar+V+COND+2+SG
> 4868 gauuharmo	gauchar+V+INF+1+PL
> 4869 gauuharmos	gauchar+V+INF+1+PL
> 4870 gauuharmos	gauchar+V+SBJF+1+PL
> 4871 gauuhará	gauchar+V+FUT+3+SG
> 4872 gauuharás	gauchar+V+FUT+2+SG
> 4873 gauuharão	gauchar+V+FUT+3+PL
> 4874 gauuharíamos	gauchar+V+COND+1+PL
> 4875 gauuharíeis	gauchar+V+COND+2+PL
> 4876 gauuhasse	gauchar+V+SBJP+1+SG
> 4877 gauuhasse	gauchar+V+SBJP+3+SG
> 4878 gauuhassem	gauchar+V+SBJP+3+PL
> 4879 gauuhasses	gauchar+V+SBJP+2+SG
> 4880 gauuhaste	gauchar+V+PRF+2+PL
> 4881 gauuhaste	gauchar+V+PRF+2+SG
> 4882 gauuhastes	gauchar+V+PRF+2+PL
> 4883 gauuhava	gauchar+V+IMPF+1+SG
> 4884 gauuhava	gauchar+V+IMPF+2+SG
> 4885 gauuhava	gauchar+V+IMPF+3+SG
> 4886 gauuhavam	gauchar+V+IMPF+3+PL
> 4887 gauuhavas	gauchar+V+IMPF+2+SG
> 4888 gauuhei	gauchar+V+PRF+1+SG
> 4889 gauuheis	gauchar+V+SBJR+2+PL
> 4890 gauuhemo	gauchar+V+IMP+1+PL
> 4891 gauuhemos	gauchar+V+IMP+1+PL
> 4892 gauuhemos	gauchar+V+SBJR+1+PL
> 4893 gauuhou	gauchar+V+PRF+3+SG
> 4894 gauuhá	gauchar+V+INF
> 4895 gauuhá	gauchar+V+INF+1+SG
> 4896 gauuhá	gauchar+V+INF+3+SG
> 4897 gauuháramo	gauchar+V+PQP+1+PL
> 4898 gauuháramos	gauchar+V+PQP+1+PL
> 4899 gauuhárei	gauchar+V+PQP+2+PL
> 4900 gauuháreis	gauchar+V+PQP+2+PL
> 4901 gauuhásseis	gauchar+V+SBJP+2+PL
> 4902 gauuhássemos	gauchar+V+SBJP+1+PL
> 4903 gauuhávamo	gauchar+V+IMPF+1+PL
> 4904 gauuhávamos	gauchar+V+IMPF+1+PL
> 4905 gauuhávei	gauchar+V+IMPF+2+PL
> 4906 gauuháveis	gauchar+V+IMPF+2+PL
> 4907 gauúha	gauchar+V+IMP+2+SG
> 4908 gauúha	gauchar+V+PRS+3+SG
> 4909 gauúham	gauchar+V+PRS+3+PL
> 4910 gauúhas	gauchar+V+PRS+2+SG
> 4911 gauúhe	gauchar+V+IMP+3+SG
> 4912 gauúhe	gauchar+V+SBJR+1+SG
> 4913 gauúhe	gauchar+V+SBJR+3+SG
> 4914 gauúhem	gauchar+V+IMP+3+PL
> 4915 gauúhem	gauchar+V+SBJR+3+PL
> 4916 gauúhes	gauchar+V+SBJR+2+SG
> 4917 gauúho	gauchar+V+PRS+1+SG
> ```
> 
> @leoalenc concorda em removermos estas entradas?

@arademaker , sim, as formas com _uu_ devem ser removidas ou, melhor, substituídas pelas formas em _uc_, i.e., em vez de _gauúhem_, devemos ter _gaúchem_, ver http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=2181.

**Comment by arademaker** [comment]
Para `benzer`, removi as formas `bents*` mas observei que ainda temos algum problema comparando com outros verbos da segunda conjugação `-er`:

```
ar@tenis verbs % grep "\tcorrer+V" * | wc -l
      90
ar@tenis verbs % grep "\tarder+V" * | wc -l
      89
ar@tenis verbs % grep "\tbenzer+V" * | wc -l
      94
ar@tenis verbs % grep "\ttorcer+V" * | wc -l
      90
```

O número de formas em uma dada conjugação não deveria ser igual?

**Comment by arademaker** [comment]
commit 2a7cfdf no branch issue-67 elimina as formas `bents*` do lema `benzer`

**Comment by arademaker** [comment]
Para gauchar, temos:

```
ar@tenis verbs % grep "\ttelefonar+V" * | wc -l
      91
ar@tenis verbs % grep "\tacordar+V" * | wc -l
      92
ar@tenis verbs % grep "\tgauchar+V" * | wc -l
     158
```

O que sugeri que as formas com `uu` devem realmente ser apagadas...

**Comment by arademaker** [comment]
confirmando, as consultas abaixo parecem sugerir que as formas `uu` estão realmente `sobrando` e devem ser simplesmente apagadas dado que as correspondentes formas `uc`

```
% awk -F "\t" '$2 ~ /^gauchar\+V\+PRF\+2\+PL/ {print $0,FILENAME}' *
gauchastes	gauchar+V+PRF+2+PL verbs-abf.dict
gauuhaste	gauchar+V+PRF+2+PL verbs-abf.dict
gauuhastes	gauchar+V+PRF+2+PL verbs-abf.dict

ar@tenis verbs % awk -F "\t" '$2 ~ /^gauchar\+V\+PRF\+2\+SG/ {print $0,FILENAME}' *
gauchaste	gauchar+V+PRF+2+SG verbs-abf.dict
gauuhaste	gauchar+V+PRF+2+SG verbs-abf.dict
```

No entanto, para o exemplo do @leoalenc acima, as formas de gauchar no `SBJR+3+PL` temos que na forma esperada segundo o [PLP](http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=2181) tem acento, mas no recurso não temos o acento. E a versão errada está com `uú`. 

```
 % awk -F "\t" '$2 ~ /^gauchar\+V\+SBJR\+3\+PL/ {print $0,FILENAME}' *
gauchem	gauchar+V+SBJR+3+PL verbs-abf.dict
gauúhem	gauchar+V+SBJR+3+PL verbs-abf.dict
``` 

@analununes eu gostaria de ter um melhor suporte computacional para corrigir o recurso. Para os verbos, dado um lema, se pudéssemos ter as conjugações mostradas como no PLP, seria bem fácil reconhecer as lacunas e/ou indevidas duplicatas de formas.

**Comment by arademaker** [comment]
Outra observação, no PLP no final da página, existe um link para a conjugação de `conjuga como enraizar`. No nosso recurso, temos 93 formas para enraizar:

```
% awk -F "\t" '$2 ~ /^enraizar\+V/ {print $0,FILENAME}' *  | wc -l
      93
```

Seria então o número esperado para `gauchar`. Mas no PLP temos 73 formas na página?! Duas formas possíveis para a `PRF+1+PL` (com e sem acento), variações de gênero e número das formas do particípio passado e duas formas para a `IMP+2+SG` e `IMP+2+PL` (identificadas entre parênteses e não separadas por `/` como as formas do `PRF`). Existe alguma forma de prevermos a quantidade de formas para cada conjugação?

**Comment by analununes** [comment]
> > E para gauchar temos também algumas várias formas com duplo `uu` suspeitas que não aparecem em https://www.conjugacao.com.br/verbo-gauchar/. Imagino que estes erros podem ter sido introduzidos no recurso e propagados pelas regras de inflexão que implementamos:
> > ```
> > 4831 gauuhada	gauchar+V+PTPST+F+SG
> > 4832 gauuhadas	gauchar+V+PTPST+F+PL
> > 4833 gauuhado	gauchar+V+PTPST+M+SG
> > 4834 gauuhados	gauchar+V+PTPST+M+PL
> > 4835 gauuhai	gauchar+V+IMP+2+PL
> > 4836 gauuhais	gauchar+V+PRS+2+PL
> > 4837 gauuhamo	gauchar+V+PRF+1+PL
> > 4838 gauuhamo	gauchar+V+PRS+1+PL
> > 4839 gauuhamos	gauchar+V+PRF+1+PL
> > 4840 gauuhamos	gauchar+V+PRS+1+PL
> > 4841 gauuhando	gauchar+V+GRD
> > 4842 gauuhar	gauchar+V+INF
> > 4843 gauuhar	gauchar+V+INF+1+SG
> > 4844 gauuhar	gauchar+V+INF+3+SG
> > 4845 gauuhar	gauchar+V+SBJF+1+SG
> > 4846 gauuhar	gauchar+V+SBJF+3+SG
> > 4847 gauuhara	gauchar+V+PQP+1+SG
> > 4848 gauuhara	gauchar+V+PQP+2+SG
> > 4849 gauuhara	gauchar+V+PQP+3+SG
> > 4850 gauuharam	gauchar+V+PQP+3+PL
> > 4851 gauuharam	gauchar+V+PRF+3+PL
> > 4852 gauuharas	gauchar+V+PQP+2+SG
> > 4853 gauuharde	gauchar+V+INF+2+PL
> > 4854 gauuhardes	gauchar+V+INF+2+PL
> > 4855 gauuhardes	gauchar+V+SBJF+2+PL
> > 4856 gauuhare	gauchar+V+INF+2+SG
> > 4857 gauuharei	gauchar+V+FUT+1+SG
> > 4858 gauuhareis	gauchar+V+FUT+2+PL
> > 4859 gauuharem	gauchar+V+INF+3+PL
> > 4860 gauuharem	gauchar+V+SBJF+3+PL
> > 4861 gauuharemos	gauchar+V+FUT+1+PL
> > 4862 gauuhares	gauchar+V+INF+2+SG
> > 4863 gauuhares	gauchar+V+SBJF+2+SG
> > 4864 gauuharia	gauchar+V+COND+1+SG
> > 4865 gauuharia	gauchar+V+COND+3+SG
> > 4866 gauuhariam	gauchar+V+COND+3+PL
> > 4867 gauuharias	gauchar+V+COND+2+SG
> > 4868 gauuharmo	gauchar+V+INF+1+PL
> > 4869 gauuharmos	gauchar+V+INF+1+PL
> > 4870 gauuharmos	gauchar+V+SBJF+1+PL
> > 4871 gauuhará	gauchar+V+FUT+3+SG
> > 4872 gauuharás	gauchar+V+FUT+2+SG
> > 4873 gauuharão	gauchar+V+FUT+3+PL
> > 4874 gauuharíamos	gauchar+V+COND+1+PL
> > 4875 gauuharíeis	gauchar+V+COND+2+PL
> > 4876 gauuhasse	gauchar+V+SBJP+1+SG
> > 4877 gauuhasse	gauchar+V+SBJP+3+SG
> > 4878 gauuhassem	gauchar+V+SBJP+3+PL
> > 4879 gauuhasses	gauchar+V+SBJP+2+SG
> > 4880 gauuhaste	gauchar+V+PRF+2+PL
> > 4881 gauuhaste	gauchar+V+PRF+2+SG
> > 4882 gauuhastes	gauchar+V+PRF+2+PL
> > 4883 gauuhava	gauchar+V+IMPF+1+SG
> > 4884 gauuhava	gauchar+V+IMPF+2+SG
> > 4885 gauuhava	gauchar+V+IMPF+3+SG
> > 4886 gauuhavam	gauchar+V+IMPF+3+PL
> > 4887 gauuhavas	gauchar+V+IMPF+2+SG
> > 4888 gauuhei	gauchar+V+PRF+1+SG
> > 4889 gauuheis	gauchar+V+SBJR+2+PL
> > 4890 gauuhemo	gauchar+V+IMP+1+PL
> > 4891 gauuhemos	gauchar+V+IMP+1+PL
> > 4892 gauuhemos	gauchar+V+SBJR+1+PL
> > 4893 gauuhou	gauchar+V+PRF+3+SG
> > 4894 gauuhá	gauchar+V+INF
> > 4895 gauuhá	gauchar+V+INF+1+SG
> > 4896 gauuhá	gauchar+V+INF+3+SG
> > 4897 gauuháramo	gauchar+V+PQP+1+PL
> > 4898 gauuháramos	gauchar+V+PQP+1+PL
> > 4899 gauuhárei	gauchar+V+PQP+2+PL
> > 4900 gauuháreis	gauchar+V+PQP+2+PL
> > 4901 gauuhásseis	gauchar+V+SBJP+2+PL
> > 4902 gauuhássemos	gauchar+V+SBJP+1+PL
> > 4903 gauuhávamo	gauchar+V+IMPF+1+PL
> > 4904 gauuhávamos	gauchar+V+IMPF+1+PL
> > 4905 gauuhávei	gauchar+V+IMPF+2+PL
> > 4906 gauuháveis	gauchar+V+IMPF+2+PL
> > 4907 gauúha	gauchar+V+IMP+2+SG
> > 4908 gauúha	gauchar+V+PRS+3+SG
> > 4909 gauúham	gauchar+V+PRS+3+PL
> > 4910 gauúhas	gauchar+V+PRS+2+SG
> > 4911 gauúhe	gauchar+V+IMP+3+SG
> > 4912 gauúhe	gauchar+V+SBJR+1+SG
> > 4913 gauúhe	gauchar+V+SBJR+3+SG
> > 4914 gauúhem	gauchar+V+IMP+3+PL
> > 4915 gauúhem	gauchar+V+SBJR+3+PL
> > 4916 gauúhes	gauchar+V+SBJR+2+SG
> > 4917 gauúho	gauchar+V+PRS+1+SG
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @leoalenc concorda em removermos estas entradas?
> 
> @arademaker , sim, as formas com _uu_ devem ser removidas ou, melhor, substituídas pelas formas em _uc_, i.e., em vez de _gauúhem_, devemos ter _gaúchem_, ver http://www.portaldalinguaportuguesa.org/index.php?action=lemma&lemma=2181.

Related to #106

**Comment by arademaker** [comment]
bu #106 is closed, so it means this can be closed too?

**Comment by analununes** [comment]
Resolvido nos commits cf40cf026a6dc8162cead7b744706c4f1403e485 e c5b009d970a87eed466c61ba1aea04b91934848c.
