### ISSUE TITLE
diminutive error in freeling

### ISSUE THREAD

**Issue by odanoburu** [LR-POR/MorphoBr#52]
```
molengu molenga AQCCS00
molengus molenga AQCCP00
```
a tag `C` marca como diminutivo.

**Comment by leoalenc** [comment]
@odanoburu conforme 

https://talp-upc.gitbooks.io/freeling-4-0-user-manual/content/tagsets/tagset-pt.html

diminutivo seria V na casa 2. Diminutivo é um tipo de sufixo avaliativo. Desse modo, o Freeling adota a visão de que os sufixos avaliativos instanciam o grau avaliativo, "evaluative" em inglês.

**Comment by leoalenc** [comment]
Acho essas entradas muito estranhas, não aparece no dicio

https://www.dicio.com.br/pesquisa.php?q=molengu

Por outro lado, desconheço palavra do português com radical em -u que tenha lema em -a.

**Comment by leoalenc** [comment]
Correção: essas formas não aparecem no Dicio nem no Infopedia

https://www.infopedia.pt/dicionarios/lingua-portuguesa/molengu

**Comment by arademaker** [comment]
commit b1273ae closes this issue.
