### ISSUE TITLE
verbos não presentes no repositório

### ISSUE THREAD

**Issue by lucasrct** [LR-POR/MorphoBr#76]
Durante algumas análises, juntei alguns verbos que não constam ainda no MorphoBr, são eles:

```
priorizar
reaglutinar
desestimular
gestar
reconfigurar
credenciar
reaparelhar
pós-graduar (?)
repactuar
superfaturar
reinstaurar
acessar
monitorar
realocar
elencar
contra-argumentar (?)
operacionalizar
reapropriar
```

**Comment by arademaker** [comment]
@leoalenc parece que todos os verbos são da primeira conjugação, já temos transdutor para geração das formas flexionadas a partir dos lemas para esta conjugação verbal? 

https://www.conjugacao.com.br/verbos-da-primeira-conjugacao-terminados-em-ar/

Os casos com hífen foram destacados pelo @lucasrct porque, por um lado, são compostos e os prefixos `pós-` e `contra-` são bem regulares e produtivos. Como lidaremos com eles?

**Comment by leoalenc** [comment]
@arademaker e @lucasrct, de fato, todos são verbos da primeira conjugação, flexionando-se, portanto, de forma regular, com poucos ajustes necessários. por exemplo, num verbo como elencar, a consoante final do radical é alterada diante de vogais frontais: eu elenquei. Essa alteração ortográfica afeta diversos outros processos morfológicos: peruca e  peruqueira. 
É interessante que muitos desses verbos levantados pelo  @lucasrct são derivados, por meio do processo produtivo da prefixação, de verbos que já constam do nosso recurso:

grep -Eh "(configurar|estimular|pactuar|aglutinar|apropriar|aparelhar)\+V\+INF$"
*.dict | awk '{print $2}' | sort | uniq
aglutinar+V+INF
aparelhar+V+INF
apropriar+V+INF
compactuar+V+INF
configurar+V+INF
contra-estimular+V+INF
contraestimular+V+INF
desaparelhar+V+INF
desapropriar+V+INF
estimular+V+INF
pactuar+V+INF

Entre 2013 e 2014, eu construí um transdutor capaz de fazer a conjugação de verbos. Isso até fez parte de um artigo que eu apresentei no Propor em São Carlos em 2014. Infelizmente, acho que me descuidei e esse arquivo ficou num velho Mac que deu pau no ano passado. Não estou encontrando um backup desses arquivos. Mas não seria difícil construir um conjugador para verbos regulares. Numa linguagem procedural, bastaria seguir os seguintes passos: número um: extrair Do recurso todas as formas do verbo comprar. Número dois: Para cada lema da lista de verbos novos, substituir o radical do verbo comprar pelo radical desse verbo. Número três: para cada lista de pares gerados pelo passo anterior, realizar os ajustes ortográficos necessários. Na primeira conjugação, parece que só são seguintes, se não estou esquecendo nada agora:

consoante c antes de vogal frontal vira qu
consoante g antes de vogal frontal vira gu

Procedimento análogo poderia ser aplicado aos verbos existentes no recurso para gerar as formas prefixadas. É preciso atentar para o fato de que, no novo acordo ortográfico, o hífen foi suprimido em determinados casos. Fiz alguma coisa parecida no meu artigo do STIL de 2015. É claro que isso vai causar um explosão no número de verbos. Uma alternativa talvez mais interessante seria construir um adivinhador de verbos sob a forma de um transdutor lexical. Mas, nesse caso, não teríamos mais o recurso como uma lista de pares.
Eu poderia fazer isso, mas não agora em julho nem no começo de agosto, Por conta de outros compromissos.

**Comment by analununes** [comment]
> Durante algumas análises, juntei alguns verbos que não constam ainda no MorphoBr, são eles:
> 
> ```
> priorizar
> reaglutinar
> desestimular
> gestar
> reconfigurar
> credenciar
> reaparelhar
> pós-graduar (?)
> repactuar
> superfaturar
> reinstaurar
> acessar
> monitorar
> realocar
> elencar
> contra-argumentar (?)
> operacionalizar
> reapropriar
> ```

No commit 6da66b2 foram adicionados as formas geradas pelas regras de [my-irules.tdl](https://github.com/LR-POR/PorGram/blob/dev/my-irules.tdl) para esses verbos.

**Comment by arademaker** [comment]
Vc incluiu ou não os dois casos com prefixo?

**Comment by analununes** [comment]
> Vc incluiu ou não os dois casos com prefixo?

@arademaker, adicionei os dois, achei que seria a melhor opção pois já havia verbos com esses prefixos nos arquivos. Você acha melhor não incluir verbos com prefixos?
