### ISSUE TITLE
PTPASS should be replaced by PTPST

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#81]
@arademaker, no DELAF_PB, K representa o particípio. Na atual versão do MorphoBr, só temos a etiqueta PTPASS, que é o particípio passivo. Não temos a etiqueta PTPST, que é o particípio passado. Enquanto grande parte dos verbos possui as duas formas, que diferem na valência, verbos intransitivos não apassiváveis como _ser_ não possuem um PTPASS. O contrário, porém, é verdadeiro: todo verbo possui PTPST. Desse modo, proponho substituir PTPASS por PTPST. Essa questão é relevante para [a discussão sobre a compatibilidade entre MorphoBr e UD](https://github.com/cpdoc/test/issues/16#issuecomment-830350646).

**Comment by arademaker** [comment]
Bom, ao fazer isso, estaremos deixando como pendências identificar quais verbos teriam o PTPASS, correto? 

Para confirmar, vc está propondo transformar PTPASS em PTPST de forma global em todos os verbos certo?

```
ar@leme verbs % rg PTPASS * | wc -l
  138576
```

Confirmando eu vou rodar:

```
for f in *.dict; do 
awk 'BEGIN {OFS="\t"} $2 ~ /PTPASS/ {sub(/PTPASS/,"PTPST",$2); print $1,$2}' $f > $f.new; done
````

E temos que corrigir o arquivo TAGSET, certo? Está confuso porque lá falamos que o K do DELAF_PB é passive participle e não apenas participio. E `passive participle (PTPST forms, i.e., past participles without gender and number tags, must be included)` sugeri que PTPST estão inclusos nos PTPASS mas vc acima diz o contrário ne? Todos os verbos tem PTPST mas nem todos PTPASS.

**Comment by leoalenc** [comment]
> Bom, ao fazer isso, estaremos deixando como pendências identificar quais verbos teriam o PTPASS, correto?
> 
> Para confirmar, vc está propondo transformar PTPASS em PTPST de forma global em todos os verbos certo?
> 
> ```
> ar@leme verbs % rg PTPASS * | wc -l
>   138576
> ```
> 
> Confirmando eu vou rodar:
> 
> ```
> for f in *.dict; do 
> awk 'BEGIN {OFS="\t"} $2 ~ /PTPASS/ {sub(/PTPASS/,"PTPST",$2); print $1,$2}' $f > $f.new; done
> ```
> 
> E temos que corrigir o arquivo TAGSET, certo? Está confuso porque lá falamos que o K do DELAF_PB é passive participle e não apenas participio. E `passive participle (PTPST forms, i.e., past participles without gender and number tags, must be included)` sugeri que PTPST estão inclusos nos PTPASS mas vc acima diz o contrário ne? Todos os verbos tem PTPST mas nem todos PTPASS.

@arademaker, na documentação do [DELAF_PB](http://www.nilc.icmc.usp.br/nilc/projects/unitex-pb/web/files/Formato_DELAF_PB.pdf), temos:

> G: Gerúndio
> K: Particípio

Gerúndio são as formas em _-ndo_, como _cantando_, e particípio, formas em _do_, como _cantado_. Agora me escapa por que converti K em PTPASS, quando construímos o MorphoBr. Parece que na época eu estava preocupado com a análise da passiva na BrGram. As documentação de UD desrecomenda o termo _gerúndio_, preferindo _particípio presente_. Com isso na cabeça, sugeri inicialmente PTPST para substituir PTPASS. Creio que podemos manter essa etiqueta, com a interpretação de UD, adotada por outros autores, ou seja, como a forma de particípio que se usa tanto para construir tempos do passado (por ex., _eu tinha cantado_) como a voz passiva (por ex., _o hino foi cantado_).  Desse modo, na documentação, teríamos simplesmente o seguinte:

> PTPST past participle

A diferença entre os dois particípios dos exemplos _eu tinha cantado_ e _o hino foi cantado_ diz respeito à valência, fenômeno fora do escopo do _POS-taging_.

**Comment by arademaker** [comment]
O commit 5bb7c47 resolve este issue. Peço verificar. No arquivo TAGSET, poderíamos tentar acrescentar o mapeamento para UD talvez... E note ainda que poderiamos buscar algum link com https://unimorph.github.io.

**Comment by leoalenc** [comment]
> O commit [5bb7c47](https://github.com/LR-POR/MorphoBr/commit/5bb7c477175b3cb071928d7666710217ae55e757) resolve este issue. Peço verificar. No arquivo TAGSET, poderíamos tentar acrescentar o mapeamento para UD talvez... E note ainda que poderiamos buscar algum link com https://unimorph.github.io, veja #54.

@arademaker, seriam úteis esses mapeamentos, até tendo em vista a checagem do MorphoBr e do Bosque UD pela comparação entre os dois recursos.

**Comment by arademaker** [comment]
OK, ja temos o issue para tratar disso. Por agora, queremos o mapeamento com UD.

**Comment by analununes** [comment]
@arademaker e @leoalenc, nos clíticos ainda existe a tag `PTPASS`, vamos atualizar?

```
provindo-a	provir+V.ele.ACC.3.F.SG+PTPASS
provindo-as	provir+V.ele.ACC.3.F.PL+GRD
provindo-as	provir+V.ele.ACC.3.F.PL+PTPASS
```

**Comment by leoalenc** [comment]
> @arademaker e @leoalenc, nos clíticos ainda existe a tag `PTPASS`, vamos atualizar?
> 
> ```
> provindo-a	provir+V.ele.ACC.3.F.SG+PTPASS
> provindo-as	provir+V.ele.ACC.3.F.PL+GRD
> provindo-as	provir+V.ele.ACC.3.F.PL+PTPASS
> ```

@analununes , bem observado, sim, vamos. A *tag* `PTPASS` não será mais utilizada, apenas `PTPST`, que, conforme expliquei em comentário anterior, serve tanto para o particípio passivo quanto particípio passado.

**Comment by arademaker** [comment]
Imagino que ao trocar a tag PTPASS por PTPST possam surgir entradas duplicadas (entradas PTPST já existentes) certo? Importante verificar isso.

**Comment by analununes** [comment]
> Imagino que ao trocar a tag PTPASS por PTPST possam surgir entradas duplicadas (entradas PTPST já existentes) certo? Importante verificar isso.

Posso cuidar disso quandoo estiver trocando a tag .

**Comment by analununes** [comment]
Conforme #118, problema de tag `PTPASS` no diretório de cliticos foi resolvido em 077f617ebae89a1c8b3cb367212eb077bc7279d9
