### ISSUE TITLE
Inconsistency in assigning the NEG tag

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#82]
@arademaker, temos os seguintes advérbios com a etiqueta NEG:

`grep -E "ADV\+NEG" adverbs/*.dict`

> jamais	jamais+ADV+NEG
> nada	nada+ADV+NEG
> nadinha	nada+ADV+NEG
> não	não+ADV+NEG

Com exceção de _nadinha_, todas essas palavras ocorrem também com a etiqueta  ADV apenas. Essa é uma ambiguidade espúria que precisa ser removida. Resultou do tratamento distinto que DELAF_PB e FreeLing conferem a essas palavras. Proponho que eliminemos as duplicatas apenas com a etiqueta ADV. Descobri essa inconsistência por meio do relatório report-morpho-bosque.txt. Trata-se de _issue_ relevante para [https://github.com/cpdoc/test/issues/16#issuecomment-832086360](https://github.com/cpdoc/test/issues/16#issuecomment-832086360 ).

**Comment by vcvpaiva** [comment]
@leoalenc esta' faltando pelo menos "quase" (Eu quase morri.=> eu nao morri) e  "sem" (um filme do James Bond sem o Sean Connery.==>  JamesBond \land not(SeanConnery))

**Comment by leoalenc** [comment]
> @leoalenc esta' faltando pelo menos "quase" (Eu quase morri.=> eu nao morri) e "sem" (um filme do James Bond sem o Sean Connery.==> JamesBond \land not(SeanConnery))

@vcvpaiva, obrigado pelo comentário. O advérbio _quase_ consta do repositório como ADV. Não sei, contudo, se seria adequado atribuir-lhe a etiqueta adicional _+NEG_, dada a sua [definição](https://www.infopedia.pt/dicionarios/lingua-portuguesa/quase). Além disso, parece ter um comportamento sintático diferente da palavras listadas acima. Compare: 

> Ela quase que morreu. 
> *Ela não que morreu. 
> *Ela jamais que morreu. 

Sobre _sem_, é uma preposição, classe ainda não abarcada pelo repositório.

**Comment by vcvpaiva** [comment]
obrigada pela resposta @leoalenc , but como sempre eu estou pensando em semantica, nao na sintaxe. e na semantica "quase" modifica fundamentalmente o valor logico da assercao, por isso que queria te-lo marcado com ADV NEG. 

da mesma forma a preposicao "SEM", que acredito que eventualmente vcs vao querer anotar tb, nao?

**Comment by arademaker** [comment]
Commit f8726f1 resolve este issue.
