### ISSUE TITLE
incorrect 2nd person imperfect forms

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#84]
@arademaker, neste [comentário](https://github.com/LR-POR/check-tools/issues/1#issue-881040558), você menciona a seguinte forma:

>chegava	chegar+V+IMPF+2+SG

Isso me pareceu muito estranho! De fato, a segunda pessoa do singular, correspondente ao pronome _tu_, deveria terminar em _s_, ver, por exemplo:

CUNHA, C.; CINTRA, L. Nova gramática do português contemporâneo. 2. ed. Rio de Janeiro: Nova Fronteira, 1985.

Sei que alguns estudiosos, ao meu ver erroneamente, tratam _você_ como pronome de segunda pessoa do singular. Ao fazê-lo, confundem sintaxe com semântica. Aprofundei essa questão no seguinte artigo:

ALENCAR, Leonel Figueiredo de. Modelação computacional de padrões variáveis de concordância em português. Revista de Estudos da Linguagem, Belo Horizonte, v. 21, n.1, p. 43-110, jan./jun. 2013.

Atualmente, temos:

`grep  -Eh "^.+ava[[:space:]].+\IMPF\+2\+SG" verbs/*.dict | wc -l`

> 13386

`grep -Ev "\+IMP\+" verbs/*.dict | grep -E "^.+[^s][[:space:]].+\+2\+SG" | wc -l `

> 79630

Tirando o _IMP_, em vários tempos ocorrem formas de _+2+SG_ não terminando em _s_, como mostra o último comando. Em português, apenas o imperativo afirmativo deve ter formas de segunda pessoa do singular não terminando em _s_. Devemos, portanto, eliminar todas as formas de segunda pessoa do singular que não terminam em _s_, exceto as do imperativo afirmativo:

`grep  -Eh "^.+[^s][[:space:]].+\+IMP\+2\+SG" verbs/*.dict`
> honra	honrar+V+IMP+2+SG
> julga	julgar+V+IMP+2+SG
> liga	ligar+V+IMP+2+SG

Curiosamente, não temos formas de segunda pessoa do plural (salvo no _IMP_) terminando em _m_ ou _ão_, apesar do pronome _vocês_ exigir essas formas, uma incoerência que, segundo parece, herdamos dos recursos que utilizamos para construir o MorphoBr:

`grep -Ev "\+IMP\+" verbs/*.dict | grep -E "^.+(m|ão)[[:space:]].+\+2\+PL" | wc -l`

> 0

Desse modo, só precisamos fazer as eliminações acima especificadas.

**Comment by arademaker** [comment]
OK, mas não seria prudente conferir se para todos os casos temos a forma terminada em `s` para a segunda pessoa do singular?  Para o exemplo que iniciou a discussão temos:

```
% rg "^chegava\t" *
verbs-aal.dict
16073:chegava	chegar+V+IMPF+1+SG
16074:chegava	chegar+V+IMPF+2+SG
16075:chegava	chegar+V+IMPF+3+SG
ar@tenis verbs % rg "^chegavas\t" *
verbs-aal.dict
16077:chegavas	chegar+V+IMPF+2+SG
```

**Comment by arademaker** [comment]
comando alternativo para achar os casos a serem eliminados:

```
% awk '$2 !~ /\+IMP\+/ && $1 !~ /s$/ && $2 ~ /\+2\+SG/ {print}' *.dict  | wc -l
   79630
```

**Comment by leoalenc** [comment]
> OK, mas não seria prudente conferir se para todos os casos temos a forma terminada em `s` para a segunda pessoa do singular? Para o exemplo que iniciou a discussão nós temos:
> 
> ```
> % rg "^chegava\t" *
> verbs-aal.dict
> 16073:chegava	chegar+V+IMPF+1+SG
> 16074:chegava	chegar+V+IMPF+2+SG
> 16075:chegava	chegar+V+IMPF+3+SG
> 
> ar@tenis verbs % rg "^chegavas\t" *
> verbs-aal.dict
> 16077:chegavas	chegar+V+IMPF+2+SG
> ```

@arademaker, sim, é bom fazer essa verificação.

**Comment by analununes** [comment]
O problema dessa issue foi tratado em #104.

**Comment by arademaker** [comment]
@analununes todas as formas mencionadas aqui são casos de formas verbais contraídas sem clítico?

**Comment by analununes** [comment]
@arademaker, @leoalenc disse acima:

> Tirando o _IMP_, em vários tempos ocorrem formas de _+2+SG_ não terminando em _s_, como mostra o último comando. Em português, apenas o imperativo afirmativo deve ter formas de segunda pessoa do singular não terminando em _s_. Devemos, portanto, eliminar todas as formas de segunda pessoa do singular que não terminam em _s_, exceto as do imperativo afirmativo:

Em #104, a [primeira regra](https://github.com/LR-POR/MorphoBr/issues/104#issuecomment-890363872) para eliminar formas espúrias se trata desse caso:

>Se +IMP+ não é parte das features de uma forma de um dado lema de verbo, eliminar a forma se a primeira ou a segunda pessoa do plural não terminar em s.
