### ISSUE TITLE
tags diferentes

### ISSUE THREAD

**Issue by analununes** [LR-POR/MorphoBr#85]
Enquanto processava os arquivos de verbos encontrei três tags (SUBJF, SUBJR e SUBJP) que não estão no TAGSET. Suponho que sejam o mesmo que `SBJF`, `SBJR` e `SBJP`. 
@leoalenc, é isso mesmo?

**Comment by leoalenc** [comment]
@analununes , no momento não estou com o computador, só com o celular, mas deve ser isso mesmo que você supôs. Mais um erro no recurso que precisa ser corrigido!￼￼￼￼

**Comment by arademaker** [comment]
problema resolvido com 

```
sed -e 's/SUBJR/SBJR/g' -i .bak1 *.dict
sed -e 's/SUBJP/SBJP/g' -i .bak2 *.dict
sed -e 's/SUBJF/SBJF/g' -i .bak3 *.dict
rm *.bak1 *.bak2 *.bak3
```

**Comment by arademaker** [comment]
commit 275668d resolveu este issue.
