### ISSUE TITLE
trailing space after some entries

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#86]
@arademaker, por acaso, verificando a questão dos prefixos de _tags_ SBJ_ versus _SUBJ_, descobri que muitas entradas têm um espaço extra no final:

`grep -Eho "\+SUBJ.+*" verbs/*.dict | sort | uniq -c`
  

> 12981 +SUBJF+1+PL
>    6227 +SUBJF+1+PL
>   12981 +SUBJF+1+SG
>    6227 +SUBJF+1+SG
> ...

`grep -Eho "\+SUBJ[^[:space:]]+*" verbs/*.dict | sort | uniq -c`
 ```
 19208 +SUBJF+1+PL
  19208 +SUBJF+1+SG
  19208 +SUBJF+2+PL
  19208 +SUBJF+2+SG
```
É algo no mínimo deselegante que talvez devêssemos corrigir.

**Comment by arademaker** [comment]
O `:space:` na regex também captura tabulação.  Veja:

```
% grep "[[:space:]]" ~/Temp/teste.txt
1	2
1  2
1   2
ar@leme verbs % grep "\s" ~/Temp/teste.txt
1	2
1  2
1   2
ar@leme verbs % grep "[ ]" ~/Temp/teste.txt
1  2
1   2
ar@leme verbs % grep "[ ]$" ~/Temp/teste.txt
1   2
```

Para o arquivo de entrada aberto no Emacs com o `whitespace-mode` onde conseguimos ver espaços como pontos e tabulação com o símbolo `>>`.  

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/86403/118848048-c4277680-b8a4-11eb-9a9b-cdbea0993430.png">

See 

```
ar@leme morpho-br % grep "[ ]$" nouns/*.dict
ar@leme morpho-br % grep "[ ]$" adjectives/*.dict
ar@leme morpho-br % grep "[ ]$" verbs/*.dict
ar@leme morpho-br % grep "[ ]$" adverbs/*.dict
ar@leme morpho-br % grep "[ ]" adverbs/*.dict
ar@leme morpho-br % grep "[ ]" verbs/*.dict
ar@leme morpho-br % grep "[ ]" nouns/*.dict
ar@leme morpho-br % grep "[ ]" adjectives/*.dict
```

Não temos espaços! apenas tabulações.
