### ISSUE TITLE
missing forms

### ISSUE THREAD

**Issue by arademaker** [LR-POR/MorphoBr#90]
https://github.com/LR-POR/MorphoBr/pull/89#issuecomment-851630349

**Comment by arademaker** [comment]
> Não está faltando fácies fácies+N+F+SG?

não, porque fáceis sempre será plural certo? no branch master agora:

```
ar@tenis morpho-br % rg "^fáceis\t" adjectives nouns verbs adverbs
adjectives/adjectives-ac.dict
18362:fáceis	fácil+A+F+PL
18363:fáceis	fácil+A+M+PL
ar@tenis morpho-br % rg "^fácil\t" adjectives nouns verbs adverbs
adverbs/adverbs.dict
9651:fácil	fácil+ADV

adjectives/adjectives-ac.dict
18364:fácil	fácil+A+F+SG
18365:fácil	fácil+A+M+SG
```

**Comment by arademaker** [comment]
> Não está faltando gama gama+N+F+PL? Estou removendo a forma `gama` como PL e adicionando `gamas` como PL. Tinha um `gamo` que estou entendendo ser erro, removi.

```
-gama   gama+N+M+PL
 gama   gama+N+M+SG
-gama   gamo+N+F+SG
+gamas  gama+N+M+PL
+gamas  gama+N+F+PL
```

**Comment by arademaker** [comment]
> Não está faltando triz triz+N+F+PL?

Estou removendo a forma `triz` como PL, trizes é o plural de triz de acordo com https://www.dicio.com.br/trizes/

```
-triz   triz+N+M+PL
```

**Comment by arademaker** [comment]
> barbica barba+N+DIM+F+PL não deveria ser barbicas barba+N+DIM+F+PL?

Removi `barbica` como PL. Removi entradas onde `barbica` tem lema `barbica` e não é DIM. 

```
-barbica        barba+N+DIM+F+PL
+barbicas       barba+N+DIM+F+PL
-barbica        barbica+N+F+SG
-barbicas       barbica+N+F+PL
-barbicha       barbicha+N+F+SG
-barbichas      barbicha+N+F+PL
```

Ficamos agora com:

```
% rg "^barbicas?\t" *
nouns/nouns-aa.dict
24624:barbicas	barba+N+DIM+F+PL
24625:barbica	barba+N+DIM+F+SG
```

**Comment by arademaker** [comment]
> Não está faltando vilanaz vilão+*+M+SG e vilanazes vilão+*+M+PL?

Como alguns casos acima, me pareceu estarem sobrando formas, mas @leoalenc pode depois confirmar. Estou atendendo a partir de https://www.normaculta.com.br/aumentativos-e-diminutivos/ que realmente é uma forma do aumentativo de vilão. Embora: https://michaelis.uol.com.br/palavra/4bqWm/vilanaz/  e https://www.dicio.com.br/vilanaz/ nada digam sobre aumentativo/diminutivo. 

Deixei no master agora apenas as formas marcadas com AUG:

```
% rg "^vilanaz(es)?\t" *
nouns/nouns-ad.dict
45746:vilanaz	vilão+N+AUG+F+SG
45747:vilanaz	vilão+N+AUG+M+SG
45748:vilanazes	vilão+N+AUG+F+PL
45749:vilanazes	vilão+N+AUG+M+PL

adjectives/adjectives-ae.dict
31806:vilanaz	vilão+A+AUG+F+SG
31807:vilanaz	vilão+A+AUG+M+SG
31808:vilanazes	vilão+A+AUG+F+PL
31809:vilanazes	vilão+A+AUG+M+PL
```

**Comment by arademaker** [comment]
Olá @leoalenc , vi seu comentário https://github.com/LR-POR/MorphoBr/pull/89#issuecomment-851693297 agora, mas veja links acima onde encontrei vilanaz como aumentativo e barbica como diminutivo (https://www.normaculta.com.br/grau-diminutivo-dos-substantivos/). Mas, obviamente, a fonte pode não ser confiável, então devemos tirar as tags AUG e DIM?

**Comment by leoalenc** [comment]
> > Não está faltando fácies fácies+N+F+SG?
> 
> não, porque fáceis sempre será plural certo? no branch master agora:
> 

@arademaker , no [dicionário](https://www.infopedia.pt/dicionarios/lingua-portuguesa/f%C3%A1cies) da Porto Editora, temos para a forma _fácies_:

> nome masculino de 2 números
> expressão da face, fisionomia, aspeto
> nome feminino de 2 números
> GEOLOGIA conjunto de caracteres litológicos e paleontológicos de uma formação geológica

Portanto, deveríamos ter não apenas

```
grep -P "^fácies\t" nouns-a*.dict
nouns-ab.dict:fácies	fácies+N+F+PL
nouns-ab.dict:fácies	fácies+N+M+PL
nouns-ab.dict:fácies	fácies+N+M+SG
```
mas também _fácies fácies+N+F+SG_.

**Comment by analununes** [comment]
> > Não está faltando gama gama+N+F+PL? Estou removendo a forma `gama` como PL e adicionando `gamas` como PL. Tinha um `gamo` que estou entendendo ser erro, removi.
> 
> ```
> -gama   gama+N+M+PL
>  gama   gama+N+M+SG
> -gama   gamo+N+F+SG
> +gamas  gama+N+M+PL
> +gamas  gama+N+F+PL
> ```
> 
> Ficamos com:
> 
> ```
> nouns/nouns-ab.dict
> 40236:gama	gama+N+F+SG
> 40237:gama	gama+N+M+SG
> 40238:gamas	gama+N+M+PL
> 40239:gamas	gama+N+F+PL
> ```

@arademaker, existe `gama   gamo+N+F+SG` nas fontes que o @leoalenc citou [aqui](https://github.com/LR-POR/MorphoBr/pull/89#issuecomment-851695200), gama como fêmea de gamo

**Comment by leoalenc** [comment]
> Olá @leoalenc , vi seu comentário [#89 (comment)](https://github.com/LR-POR/MorphoBr/pull/89#issuecomment-851693297) agora, mas veja links acima onde encontrei vilanaz como aumentativo e barbica como diminutivo (https://www.normaculta.com.br/grau-diminutivo-dos-substantivos/). Mas, obviamente, a fonte pode não ser confiável, então devemos tirar as tags AUG e DIM?

@arademaker , _barbica_ é diminutivo, i.e., "pequena barba" [aqui](https://www.infopedia.pt/dicionarios/lingua-portuguesa/barbica). Nenhum dicionário que consultei analisa _vilanaz_ como aumentativo. O sufixo _az_ é um legítimo aumentativo em _velhacaz_, por exemplo, ver [aqui](https://www.aulete.com.br/velhacaz).

**Comment by arademaker** [comment]
Hum,  estou vendo agora confusão que fiz com `fáceis` vs `fácies`.

**Comment by arademaker** [comment]
Sim, https://www.infopedia.pt/dicionarios/lingua-portuguesa/barbica diz que é pequena barba, mas não tem nenhuma tag ou marcação geral para diminutivos e aumentativos. Mas então vou manter barbica apenas como diminutivo.

**Comment by arademaker** [comment]
Para vilanaz, em https://github.com/LR-POR/MorphoBr/pull/89#issuecomment-851693297 vc só fala das entradas como ADJ, é isso mesmo? Devemos remover entradas NOUN?

**Comment by arademaker** [comment]
Ficamos agora com

```
nouns/nouns-ad.dict
45746vilanaz	vilanaz+N+F+SG
45747vilanaz	vilanaz+N+M+SG
45748vilanazes	vilanaz+N+F+PL
45749vilanazes	vilanaz+N+M+PL

adjectives/adjectives-ae.dict
31806vilanaz	vilanaz+A+F+SG
31807vilanaz	vilanaz+A+M+SG
31808vilanazes	vilanaz+A+F+PL
31809vilanazes	vilanaz+A+M+PL

```

**Comment by leoalenc** [comment]
> > > Não está faltando gama gama+N+F+PL? Estou removendo a forma `gama` como PL e adicionando `gamas` como PL. Tinha um `gamo` que estou entendendo ser erro, removi.
> > 
> > 
> > ```
> > -gama   gama+N+M+PL
> >  gama   gama+N+M+SG
> > -gama   gamo+N+F+SG
> > +gamas  gama+N+M+PL
> > +gamas  gama+N+F+PL
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ficamos com:
> > ```
> > nouns/nouns-ab.dict
> > 40236:gama	gama+N+F+SG
> > 40237:gama	gama+N+M+SG
> > 40238:gamas	gama+N+M+PL
> > 40239:gamas	gama+N+F+PL
> > ```
> 
> @arademaker, existe `gama gamo+N+F+SG` nas fontes que o @leoalenc citou [aqui](https://github.com/LR-POR/MorphoBr/pull/89#issuecomment-851695200), gama como fêmea de gamo

Sim, @analununes e @arademaker , _gama_ como fêmea do _gamo_ (animal). Independentemente disso, ver [aqui](https://www.infopedia.pt/dicionarios/lingua-portuguesa/gama):

> nome feminino
> 1.	interseção da eclíptica com o plano do equador
> 2.	MÚSICA extensão completa dos sons musicais
> 3.	MÚSICA antiquado nota sol
> 4.	figurado série, sucessão
> nome masculino
> 1.	nome da terceira letra do alfabeto grego (γ, Γ), correspondente ao g
> 2.	FÍSICA unidade de medida, de símbolo γ, equivalente a 1 nanotesla (10-9 T), utilizada no estudo do campo magnético terrestre

Cada um desses tem plural também... Portanto, deveríamos ter exatamente isto:

> gama	gama+N+F+SG
> gama	gama+N+M+SG
> gamas	gama+N+F+PL
> gamas	gama+N+M+PL
> gama	gamo+N+F+SG
> gamas	gamo+N+F+PL

Esta entrada parece inexistir no português, deve ser coisa gerada automaticamente de corpus , ver _raios gama_  ou _ondas gama_ (N como aposto, subendente-se "raios do tipo gama" etc., ou _MWE_):

> gama	gama+N+M+PL (eliminar)

**Comment by arademaker** [comment]
acho que o cdae607 fecha este issue.

**Comment by arademaker** [comment]
notem que modifiquei branch master.

**Comment by leoalenc** [comment]
> Ficamos agora com
> 
> ```
> nouns/nouns-ad.dict
> 45746vilanaz	vilanaz+N+F+SG
> 45747vilanaz	vilanaz+N+M+SG
> 45748vilanazes	vilanaz+N+F+PL
> 45749vilanazes	vilanaz+N+M+PL
> 
> adjectives/adjectives-ae.dict
> 31806vilanaz	vilanaz+A+F+SG
> 31807vilanaz	vilanaz+A+M+SG
> 31808vilanazes	vilanaz+A+F+PL
> 31809vilanazes	vilanaz+A+M+PL
> ```

@arademaker , correto, segundo o tradicional dicionário da Porto, a principal editora lusitana na área de lexicografia. [Veja](https://www.infopedia.pt/dicionarios/lingua-portuguesa/vilanaz):

> vi.la.nazvilɐˈnaʃ
> adjetivo, nome de 2 géneros
> que ou aquele que tem características de vilão
> Do baixo latim villānu-, «vilão» +-az

Isso está de acordo com as minhas edições de papel do Houaiss e do Aurélio, que também não analisam o sufixo _az_ como aumentativo nesse caso, mas mero formador de adjetivo. O adjetivo assim formado, por sua vez, como muitos outros adjetivos, tem emprego também substantival.

**Comment by vcvpaiva** [comment]
@Leonel Figueiredo de Alencar ***@***.***>
 todos os adjetivos tem emprego tb substantival, nao?

**Comment by leoalenc** [comment]
> @LeoNel Figueiredo de Alencar ***@***.***> todos os adjetivos tem emprego tb substantival, nao?

@vcvpaiva , de certo modo, sim. Todo adjetivo pode ocorrer numa construção como esta:

>Ela comprou o crisântemo vermelho e rejeitou _o murcho_.

Nesse exemplo, pode-se dizer que _murcho_ tem emprego substantival, numa dada acepção desse termo. No entanto, pode-se dizer também que há uma categoria vazia nesse NP em relação anafórica com _crisântemo_, pelo que _murcho_ é um adjetivo. Compare com:

>A cheia do rio inundou as casas.

É a esse tipo de emprego substantival que me refiro. Esses casos devem ser incluídos num recurso lexical.
