### ISSUE TITLE
incorrect feminine form of superlatives

### ISSUE THREAD

**Issue by leoalenc** [LR-POR/MorphoBr#92]
@arademaker , ao fazer um levantamento dos substantivos como _dentista_ e adjetivos como _feliz_ que têm a mesma forma para os dois gêneros, procurando por sequências finais de _tags_ como A+SG, A+PL, N+SG etc., deparei-me com estes dois erros:

```
grep -P "\+A\+(SG|PL)[^[:space:]]" simplified-adjectives.dict 
doctiloquentíssimos	doctiloquente+A+PL+SUPER
doctiloqüentíssimos	doctiloqüente+A+PL+SUPER
```
Na simplificação por meio da versão corrigida do meu script, temos;

```
grep -Ph "\+A\+SUPER\+(SG|PL)" new-adjectives.dict 
doctiloquentíssimo	doctiloquente+A+SUPER+SG
doctiloquentíssimos	doctiloquente+A+SUPER+PL
doctiloqüentíssimo	doctiloqüente+A+SUPER+SG
doctiloqüentíssimos	doctiloqüente+A+SUPER+PL
```

Na versão original, temos:

```
grep -Ph "^doctiloq[üu]entíssim" adjectives-a*.dict
doctiloquentíssimo	doctiloquente+A+SUPER+F+SG
doctiloquentíssimo	doctiloquente+A+SUPER+M+SG
doctiloquentíssimos	doctiloquente+A+SUPER+F+PL
doctiloquentíssimos	doctiloquente+A+SUPER+M+PL
doctiloqüentíssimo	doctiloqüente+A+SUPER+F+SG
doctiloqüentíssimo	doctiloqüente+A+SUPER+M+SG
doctiloqüentíssimos	doctiloqüente+A+SUPER+F+PL
doctiloqüentíssimos	doctiloqüente+A+SUPER+M+PL
```
O feminino tem de terminar em _a_ (singular) ou _as_ (plural). O correto, portanto, é:

doctiloquentíssima	doctiloquente+A+SUPER+F+SG
doctiloquentíssimas	doctiloquente+A+SUPER+F+PL

Essa correção exige, @analununes , rodar de novo o programa de simplificação. 
Outra questão mais geral, para reflexão futura, é se queremos manter as formas da velha ortografia com _ü_.

**Comment by arademaker** [comment]
O 6629be4 resolve este issue.

**Comment by arademaker** [comment]
Em c02e6b3 corrigi também as formas `doctiloqüente` com `ü` considerando agora que por agora queremos manter a antiga e nova grafia.
